# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.property_dto_format import PropertyDTOFormat

class TestPropertyDTOFormat(unittest.TestCase):
    """PropertyDTOFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyDTOFormat:
        """Test PropertyDTOFormat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyDTOFormat`
        """
        model = PropertyDTOFormat()
        if include_optional:
            return PropertyDTOFormat(
                label = '',
                name = '',
                icon = '',
                type = '',
                settings = [
                    caraer_client.models.setting_field.SettingField(
                        name = '', 
                        label = '', 
                        help_text = '', 
                        type = 'STRING', 
                        required = True, 
                        dynamic = True, 
                        hidden = True, 
                        disabled = True, 
                        options = [
                            caraer_client.models.setting_option.SettingOption(
                                name = '', 
                                label = '', 
                                help_text = '', )
                            ], 
                        value = null, 
                        default_value = null, )
                    ],
                filters = [
                    ''
                    ],
                rules = [
                    ''
                    ],
                linked_property = caraer_client.models.property_dto.PropertyDTO(
                    uuid = '0', 
                    name = '', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    description = '', 
                    type = '', 
                    options = [
                        caraer_client.models.property_option.PropertyOption(
                            name = '', 
                            label = '', 
                            icon = '', 
                            color = '', 
                            disabled = True, 
                            completed = True, 
                            used_in = caraer_client.models.used_in_result.UsedInResult(
                                record_uuids = [
                                    ''
                                    ], 
                                count = 56, ), )
                        ], 
                    group = '', 
                    format = null, 
                    rules = [
                        ''
                        ], 
                    immutable = True, 
                    hidden = True, 
                    lifecycle_active = True, 
                    required_filter = null, 
                    non_public = True, 
                    indexed = True, 
                    editable = True, 
                    format_settings = {
                        'key' : null
                        }, 
                    used_in = null, 
                    icon = '', 
                    webpage_public = True, 
                    embeddable = True, 
                    sensitive = True, 
                    min_and_max_value = null, 
                    pinned = True, ),
                checkbox_property = caraer_client.models.property_dto.PropertyDTO(
                    uuid = '0', 
                    name = '', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    description = '', 
                    type = '', 
                    options = [
                        caraer_client.models.property_option.PropertyOption(
                            name = '', 
                            label = '', 
                            icon = '', 
                            color = '', 
                            disabled = True, 
                            completed = True, 
                            used_in = caraer_client.models.used_in_result.UsedInResult(
                                record_uuids = [
                                    ''
                                    ], 
                                count = 56, ), )
                        ], 
                    group = '', 
                    format = null, 
                    rules = [
                        ''
                        ], 
                    immutable = True, 
                    hidden = True, 
                    lifecycle_active = True, 
                    required_filter = null, 
                    non_public = True, 
                    indexed = True, 
                    editable = True, 
                    format_settings = {
                        'key' : null
                        }, 
                    used_in = null, 
                    icon = '', 
                    webpage_public = True, 
                    embeddable = True, 
                    sensitive = True, 
                    min_and_max_value = null, 
                    pinned = True, )
            )
        else:
            return PropertyDTOFormat(
        )
        """

    def testPropertyDTOFormat(self):
        """Test PropertyDTOFormat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
