# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.show_response_notification_inbox_dto import ShowResponseNotificationInboxDTO

class TestShowResponseNotificationInboxDTO(unittest.TestCase):
    """ShowResponseNotificationInboxDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShowResponseNotificationInboxDTO:
        """Test ShowResponseNotificationInboxDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShowResponseNotificationInboxDTO`
        """
        model = ShowResponseNotificationInboxDTO()
        if include_optional:
            return ShowResponseNotificationInboxDTO(
                message = 'Success',
                data = caraer_client.models.notification_inbox_dto.NotificationInboxDTO(
                    notifications = [
                        caraer_client.models.item.Item(
                            id = '', 
                            title = '', 
                            body = '', 
                            type = '', 
                            icon = '', 
                            action_title = '', 
                            action = '', 
                            data = {
                                'key' : null
                                }, 
                            sender = '', 
                            company = '', 
                            target_user_uuid = '', 
                            created_at = '', 
                            updated_at = '', 
                            read_at = '', 
                            source_app_uuid = '', 
                            app_logo = '', )
                        ], 
                    unread_count = 56, )
            )
        else:
            return ShowResponseNotificationInboxDTO(
        )
        """

    def testShowResponseNotificationInboxDTO(self):
        """Test ShowResponseNotificationInboxDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
