# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.app_billing_summary_dto import AppBillingSummaryDTO

class TestAppBillingSummaryDTO(unittest.TestCase):
    """AppBillingSummaryDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppBillingSummaryDTO:
        """Test AppBillingSummaryDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppBillingSummaryDTO`
        """
        model = AppBillingSummaryDTO()
        if include_optional:
            return AppBillingSummaryDTO(
                installation_count = 56,
                projected_revenue_total = 1.337
            )
        else:
            return AppBillingSummaryDTO(
        )
        """

    def testAppBillingSummaryDTO(self):
        """Test AppBillingSummaryDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
