# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.advanced_record_query_request import AdvancedRecordQueryRequest

class TestAdvancedRecordQueryRequest(unittest.TestCase):
    """AdvancedRecordQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvancedRecordQueryRequest:
        """Test AdvancedRecordQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvancedRecordQueryRequest`
        """
        model = AdvancedRecordQueryRequest()
        if include_optional:
            return AdvancedRecordQueryRequest(
                question = '',
                plan = caraer_client.models.advanced_record_query_plan.AdvancedRecordQueryPlan(
                    version = 56, 
                    main_object = '', 
                    main_objects = [
                        ''
                        ], 
                    query = '', 
                    filter = caraer_client.models.filter.Filter(
                        groups = [
                            caraer_client.models.filter_group.FilterGroup(
                                items = null, )
                            ], ), 
                    sort = [
                        caraer_client.models.sort_item.SortItem(
                            object = 'User', 
                            relation = 'hasProperty', 
                            relation_direction = 'outgoing', 
                            property = 'email', 
                            direction = 'ASC', )
                        ], 
                    show = [
                        caraer_client.models.show_item.ShowItem(
                            object = 'User', 
                            relation = 'hasProperty', 
                            relation_direction = 'outgoing', 
                            property = 'email', 
                            separator = '|', 
                            sticky = True, 
                            width = 100, 
                            calculation_function = 'max', 
                            calculation_result = 100, )
                        ], 
                    strategy = 'AUTO', 
                    anchor_record_uuid = '', 
                    criteria = [
                        ''
                        ], 
                    graph_traversals = [
                        caraer_client.models.graph_traversal_spec.GraphTraversalSpec(
                            relation = '', 
                            target_object = '', 
                            direction = '', 
                            max_depth = 56, 
                            include_lifecycle = True, 
                            include_activities = True, 
                            per_relation_limit = 56, )
                        ], 
                    score_weights = {
                        'key' : 1.337
                        }, 
                    include_evidence = True, 
                    max_traversal_depth = 56, 
                    page = 56, 
                    limit = 56, ),
                main_object = '',
                main_objects = [
                    ''
                    ],
                strategy = 'AUTO',
                page = 56,
                limit = 56,
                preview = '',
                parse = None,
                archived = True,
                explain = True,
                record_return_format = ''
            )
        else:
            return AdvancedRecordQueryRequest(
        )
        """

    def testAdvancedRecordQueryRequest(self):
        """Test AdvancedRecordQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
