# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.api.serverless_functions_api import ServerlessFunctionsApi


class TestServerlessFunctionsApi(unittest.TestCase):
    """ServerlessFunctionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerlessFunctionsApi()

    def tearDown(self) -> None:
        pass

    def test_create1(self) -> None:
        """Test case for create1

        Create a serverless function
        """
        pass

    def test_index2(self) -> None:
        """Test case for index2

        List serverless functions for an app
        """
        pass

    def test_show(self) -> None:
        """Test case for show

        Get a serverless function
        """
        pass

    def test_test_serverless_function(self) -> None:
        """Test case for test_serverless_function

        Test a serverless function
        """
        pass

    def test_update1(self) -> None:
        """Test case for update1

        Update a serverless function
        """
        pass


if __name__ == '__main__':
    unittest.main()
