# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.page_content_settings_dto import PageContentSettingsDTO

class TestPageContentSettingsDTO(unittest.TestCase):
    """PageContentSettingsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageContentSettingsDTO:
        """Test PageContentSettingsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageContentSettingsDTO`
        """
        model = PageContentSettingsDTO()
        if include_optional:
            return PageContentSettingsDTO(
                form = caraer_client.models.form_dto.FormDTO(
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    object = null, 
                    grids = [
                        caraer_client.models.form_item_dto.FormItemDTO(
                            aiprompt = '', 
                            title = '', 
                            description = '', 
                            type = '', 
                            ai_prompt = '', 
                            grid = [
                                [
                                    caraer_client.models.grid_item_dto.GridItemDTO(
                                        property = null, 
                                        text = '', 
                                        form = null, 
                                        submit_button = '', 
                                        settings = null, 
                                        value = '', )
                                    ]
                                ], )
                        ], 
                    description = '', 
                    styling = '', 
                    leadscores = [
                        caraer_client.models.leadscore.Leadscore(
                            object = 'User', 
                            relation = 'hasProperty', 
                            property = 'email', 
                            relation_included = True, 
                            operator = 'EQUALS', 
                            value = null, 
                            smart_content = True, 
                            smart_value = True, 
                            score = 10, )
                        ], 
                    relations = [
                        caraer_client.models.form_relation_dto.FormRelationDTO(
                            type = 'CONVERSION_PAGE_RECORD', 
                            relation = null, 
                            related_relation = null, 
                            related_object = null, 
                            record_uuid = 'fc453abc-123e-4567-890a-6789abcd1234', 
                            related_object_connection = 'PRIMARY', )
                        ], 
                    wizard = True, 
                    metadata = {
                        'key' : ''
                        }, 
                    thank_you_message = '', 
                    redirect_url = '', ),
                open_icon = '',
                close_icon = '',
                alt = '',
                key = '',
                play_video = True,
                start_muted = True,
                loop_video = True,
                start_offset = 56,
                link = '',
                style = '',
                cta_id = '',
                open_in_new_window = True,
                slider_type = '',
                carousel_speed = 1.337,
                enable_controls = True,
                preview_object = caraer_client.models.caraer_object_dto.CaraerObjectDTO(
                    uuid = '0', 
                    name = '', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    plural = '', 
                    description = '', 
                    groups = [
                        ''
                        ], 
                    icon = '', 
                    show_in_menu = True, 
                    default_trait = '', 
                    traits = [
                        ''
                        ], 
                    views = [
                        caraer_client.models.view_dto.ViewDTO(
                            uuid = '0', 
                            name = '', 
                            label = '', 
                            created_at = 56, 
                            created_by = null, 
                            updated_at = 56, 
                            updated_by = null, 
                            deleted_at = 56, 
                            deleted_by = null, 
                            index = 56, 
                            favorite = True, 
                            team = True, 
                            shared = True, 
                            personal = True, 
                            trait = '', 
                            filters = caraer_client.models.filter.Filter(), 
                            shows = [
                                caraer_client.models.show_item.ShowItem(
                                    object = 'User', 
                                    relation = 'hasProperty', 
                                    property = 'email', 
                                    separator = '|', 
                                    sticky = True, 
                                    width = 100, 
                                    calculation_function = 'max', 
                                    calculation_result = null, )
                                ], 
                            sorts = [
                                caraer_client.models.sort_item.SortItem(
                                    object = 'User', 
                                    relation = 'hasProperty', 
                                    property = 'email', 
                                    direction = 'ASC', )
                                ], 
                            limit = 56, 
                            show_icons = True, 
                            row_height = '', 
                            query = '', 
                            icon = '', 
                            flow_property = '', 
                            flow_preview = '', 
                            default_view = True, 
                            is_internally_public = True, )
                        ], 
                    properties = [
                        caraer_client.models.property_dto.PropertyDTO(
                            uuid = '0', 
                            name = '', 
                            label = '', 
                            created_at = 56, 
                            created_by = null, 
                            updated_at = 56, 
                            updated_by = null, 
                            deleted_at = 56, 
                            deleted_by = null, 
                            index = 56, 
                            description = '', 
                            type = '', 
                            options = [
                                caraer_client.models.property_option.PropertyOption(
                                    name = '', 
                                    label = '', 
                                    icon = '', 
                                    color = '', 
                                    disabled = True, 
                                    used_in = caraer_client.models.used_in_result.UsedInResult(
                                        record_uuids = [
                                            ''
                                            ], 
                                        count = 56, ), )
                                ], 
                            group = '', 
                            format = null, 
                            rules = [
                                ''
                                ], 
                            immutable = True, 
                            hidden = True, 
                            lifecycle_active = True, 
                            non_public = True, 
                            indexed = True, 
                            editable = True, 
                            format_settings = {
                                'key' : null
                                }, 
                            used_in = null, 
                            icon = '', 
                            webpage_public = True, 
                            embeddable = True, 
                            min_and_max_value = null, 
                            pinned = True, )
                        ], 
                    relations = [
                        caraer_client.models.relation_dto.RelationDTO(
                            uuid = '0', 
                            name = '', 
                            label = '', 
                            created_at = 56, 
                            created_by = null, 
                            updated_at = 56, 
                            updated_by = null, 
                            deleted_at = 56, 
                            deleted_by = null, 
                            index = 56, 
                            description = '', 
                            objects = [
                                caraer_client.models.caraer_object_dto.CaraerObjectDTO(
                                    uuid = '0', 
                                    name = '', 
                                    label = '', 
                                    created_at = 56, 
                                    created_by = null, 
                                    updated_at = 56, 
                                    updated_by = null, 
                                    deleted_at = 56, 
                                    deleted_by = null, 
                                    index = 56, 
                                    plural = '', 
                                    description = '', 
                                    icon = '', 
                                    show_in_menu = True, 
                                    default_trait = '', 
                                    suites = [
                                        ''
                                        ], 
                                    extends_to = [
                                        
                                        ], 
                                    editable = True, )
                                ], 
                            immutable = True, 
                            editable = True, )
                        ], 
                    suites = [
                        ''
                        ], 
                    extends_to = [
                        
                        ], 
                    editable = True, ),
                previews = {
                    'key' : caraer_client.models.preview_dto.PreviewDTO(
                        description = 'Preview description example', 
                        object = null, 
                        record_uuid = 'abcdef12-3456-7890-abcd-ef1234567890', 
                        primary = True, 
                        grid = [
                            [
                                caraer_client.models.preview_item_dto.PreviewItemDTO(
                                    property = null, 
                                    text = 'Sample text', 
                                    value = null, 
                                    related_object = null, 
                                    related_object_value = null, 
                                    divider = 'solid', 
                                    button_text = 'Sample text', 
                                    button_url = 'https://www.google.com', 
                                    button_text_value = null, 
                                    button_url_value = null, 
                                    settings = null, 
                                    styling = null, )
                                ]
                            ], 
                        preview_type = 'detail', 
                        profile_image = null, 
                        profile_image_position = 'top', 
                        profile_image_styling = null, 
                        first_initial_property = null, 
                        second_initial_property = null, 
                        profile_image_value = '', 
                        first_initial_property_value = '', 
                        second_initial_property_value = '', 
                        custom_css = '', 
                        url = '', 
                        styling = null, 
                        sort_property = '', 
                        sort_value = null, 
                        uuid = '0', 
                        name = '0', 
                        label = '', 
                        created_at = 56, 
                        created_by = null, 
                        updated_at = 56, 
                        updated_by = null, 
                        deleted_at = 56, 
                        deleted_by = null, 
                        index = 56, )
                    },
                preview_layout_order = [
                    ''
                    ],
                filter = caraer_client.models.filter.Filter(
                    groups = [
                        caraer_client.models.filter_group.FilterGroup(
                            items = null, )
                        ], ),
                order_by = caraer_client.models.property_dto.PropertyDTO(
                    uuid = '0', 
                    name = '', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    description = '', 
                    type = '', 
                    options = [
                        caraer_client.models.property_option.PropertyOption(
                            name = '', 
                            label = '', 
                            icon = '', 
                            color = '', 
                            disabled = True, 
                            used_in = caraer_client.models.used_in_result.UsedInResult(
                                record_uuids = [
                                    ''
                                    ], 
                                count = 56, ), )
                        ], 
                    group = '', 
                    format = null, 
                    rules = [
                        ''
                        ], 
                    immutable = True, 
                    hidden = True, 
                    lifecycle_active = True, 
                    non_public = True, 
                    indexed = True, 
                    editable = True, 
                    format_settings = {
                        'key' : null
                        }, 
                    used_in = null, 
                    icon = '', 
                    webpage_public = True, 
                    embeddable = True, 
                    min_and_max_value = null, 
                    pinned = True, ),
                order_by_direction = '',
                as_webpages = True,
                loop = True,
                limit = 56,
                group_by = caraer_client.models.property_dto.PropertyDTO(
                    uuid = '0', 
                    name = '', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    description = '', 
                    type = '', 
                    options = [
                        caraer_client.models.property_option.PropertyOption(
                            name = '', 
                            label = '', 
                            icon = '', 
                            color = '', 
                            disabled = True, 
                            used_in = caraer_client.models.used_in_result.UsedInResult(
                                record_uuids = [
                                    ''
                                    ], 
                                count = 56, ), )
                        ], 
                    group = '', 
                    format = null, 
                    rules = [
                        ''
                        ], 
                    immutable = True, 
                    hidden = True, 
                    lifecycle_active = True, 
                    non_public = True, 
                    indexed = True, 
                    editable = True, 
                    format_settings = {
                        'key' : null
                        }, 
                    used_in = null, 
                    icon = '', 
                    webpage_public = True, 
                    embeddable = True, 
                    min_and_max_value = null, 
                    pinned = True, ),
                hide_on_no_results = True,
                filter_type = '',
                search_result_single_string = '',
                search_result_plural_string = '',
                no_results_string = '',
                search_field_enabled = True,
                search_field_placeholder = '',
                filter_block_enabled = True,
                filter_title = '',
                filter_subtitle = '',
                filter_properties = [
                    caraer_client.models.property_dto.PropertyDTO(
                        uuid = '0', 
                        name = '', 
                        label = '', 
                        created_at = 56, 
                        created_by = null, 
                        updated_at = 56, 
                        updated_by = null, 
                        deleted_at = 56, 
                        deleted_by = null, 
                        index = 56, 
                        description = '', 
                        type = '', 
                        options = [
                            caraer_client.models.property_option.PropertyOption(
                                name = '', 
                                label = '', 
                                icon = '', 
                                color = '', 
                                disabled = True, 
                                used_in = caraer_client.models.used_in_result.UsedInResult(
                                    record_uuids = [
                                        ''
                                        ], 
                                    count = 56, ), )
                            ], 
                        group = '', 
                        format = null, 
                        rules = [
                            ''
                            ], 
                        immutable = True, 
                        hidden = True, 
                        lifecycle_active = True, 
                        non_public = True, 
                        indexed = True, 
                        editable = True, 
                        format_settings = {
                            'key' : null
                            }, 
                        used_in = null, 
                        icon = '', 
                        webpage_public = True, 
                        embeddable = True, 
                        min_and_max_value = null, 
                        pinned = True, )
                    ],
                enable_filter_tiles = True,
                enable_filter_query = True,
                enable_remove_all_filters_button = True,
                cta_enabled = True,
                cta_title = '',
                cta_text = '',
                cta_button_text = '',
                cta_button_link = '',
                platforms = [
                    ''
                    ]
            )
        else:
            return PageContentSettingsDTO(
        )
        """

    def testPageContentSettingsDTO(self):
        """Test PageContentSettingsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
