# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.test_webhook_request import TestWebhookRequest

class TestTestWebhookRequest(unittest.TestCase):
    """TestWebhookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestWebhookRequest:
        """Test TestWebhookRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestWebhookRequest`
        """
        model = TestWebhookRequest()
        if include_optional:
            return TestWebhookRequest(
                webhook = caraer_client.models.subscribe_webhook_dto.SubscribeWebhookDTO(
                    url = 'https://example.com/webhook', 
                    serverless_function = null, 
                    delivery_mode = '', 
                    secret = 'abcd1234', 
                    topic = 'user.created', 
                    description = '', 
                    webhook_format = 'LEGACY', 
                    parse_record = True, 
                    filter = null, 
                    include_relations = [candidate, vacancy], 
                    relation_filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    relation_limit = 10, 
                    retry_enabled = True, 
                    max_retries = 3, 
                    retry_backoff_ms = 1000, 
                    trigger_offset_seconds = 604800, 
                    schedule_direction = 'BEFORE', 
                    schedule_recurring = 'YEARLY', 
                    schedule_cron_expression = '0', 
                    schedule_version = 56, 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
                record_uuid = 'record-uuid',
                event_type = 'created',
                property_name = 'status'
            )
        else:
            return TestWebhookRequest(
                webhook = caraer_client.models.subscribe_webhook_dto.SubscribeWebhookDTO(
                    url = 'https://example.com/webhook', 
                    serverless_function = null, 
                    delivery_mode = '', 
                    secret = 'abcd1234', 
                    topic = 'user.created', 
                    description = '', 
                    webhook_format = 'LEGACY', 
                    parse_record = True, 
                    filter = null, 
                    include_relations = [candidate, vacancy], 
                    relation_filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    relation_limit = 10, 
                    retry_enabled = True, 
                    max_retries = 3, 
                    retry_backoff_ms = 1000, 
                    trigger_offset_seconds = 604800, 
                    schedule_direction = 'BEFORE', 
                    schedule_recurring = 'YEARLY', 
                    schedule_cron_expression = '0', 
                    schedule_version = 56, 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
        )
        """

    def testTestWebhookRequest(self):
        """Test TestWebhookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
