# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.api.forms_api import FormsApi


class TestFormsApi(unittest.TestCase):
    """FormsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FormsApi()

    def tearDown(self) -> None:
        pass

    def test_chat_field(self) -> None:
        """Test case for chat_field

        AI form field (public)
        """
        pass

    def test_chat_step(self) -> None:
        """Test case for chat_step

        AI form step (public)
        """
        pass

    def test_create_form(self) -> None:
        """Test case for create_form

        Create a new form
        """
        pass

    def test_delete_form(self) -> None:
        """Test case for delete_form

        Delete a form
        """
        pass

    def test_get_form(self) -> None:
        """Test case for get_form

        Get form by UUID
        """
        pass

    def test_get_form_public(self) -> None:
        """Test case for get_form_public

        Get form by UUID
        """
        pass

    def test_get_forms(self) -> None:
        """Test case for get_forms

        Get paginated list of forms
        """
        pass

    def test_get_forms_by_object(self) -> None:
        """Test case for get_forms_by_object

        Get forms by object UUID
        """
        pass

    def test_get_forms_public(self) -> None:
        """Test case for get_forms_public

        Get all forms for a company
        """
        pass

    def test_get_objects_with_forms(self) -> None:
        """Test case for get_objects_with_forms

        List objects that have forms
        """
        pass

    def test_get_options(self) -> None:
        """Test case for get_options

        Property options (public)
        """
        pass

    def test_restore_form(self) -> None:
        """Test case for restore_form

        Restore a deleted form
        """
        pass

    def test_submit(self) -> None:
        """Test case for submit

        Submit a form
        """
        pass

    def test_update_form(self) -> None:
        """Test case for update_form

        Update an existing form
        """
        pass

    def test_upload_files(self) -> None:
        """Test case for upload_files

        Submit a file
        """
        pass


if __name__ == '__main__':
    unittest.main()
