# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.api.webpages_api import WebpagesApi


class TestWebpagesApi(unittest.TestCase):
    """WebpagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebpagesApi()

    def tearDown(self) -> None:
        pass

    def test_claim_template_webpage_editing_session(self) -> None:
        """Test case for claim_template_webpage_editing_session

        Claim a template webpage editing session
        """
        pass

    def test_claim_webpage_editing_session(self) -> None:
        """Test case for claim_webpage_editing_session

        Claim a webpage editing session
        """
        pass

    def test_copy_property_to_environments(self) -> None:
        """Test case for copy_property_to_environments

        Copy properties to environments
        """
        pass

    def test_copy_template_webpage(self) -> None:
        """Test case for copy_template_webpage

        Copy a template webpage from one environment to another
        """
        pass

    def test_copy_webpage(self) -> None:
        """Test case for copy_webpage

        Copy a webpage from one environment to another
        """
        pass

    def test_create_environments(self) -> None:
        """Test case for create_environments

        Create an environment
        """
        pass

    def test_create_or_update_template_webpage(self) -> None:
        """Test case for create_or_update_template_webpage

        Create or update template webpage
        """
        pass

    def test_create_signed_url(self) -> None:
        """Test case for create_signed_url

        Generate signed URL for protected webpage
        """
        pass

    def test_create_webpage(self) -> None:
        """Test case for create_webpage

        Create a new webpage
        """
        pass

    def test_delete_environment(self) -> None:
        """Test case for delete_environment

        Delete an environment
        """
        pass

    def test_get_all_slugs(self) -> None:
        """Test case for get_all_slugs

        Get all public webpage slugs
        """
        pass

    def test_get_company_settings(self) -> None:
        """Test case for get_company_settings

        Fetch public company settings
        """
        pass

    def test_get_environments(self) -> None:
        """Test case for get_environments

        Get all environments
        """
        pass

    def test_get_menus(self) -> None:
        """Test case for get_menus

        Fetch public web menus
        """
        pass

    def test_get_public_custom_footer_module(self) -> None:
        """Test case for get_public_custom_footer_module

        Fetch public custom footer module
        """
        pass

    def test_get_public_previews(self) -> None:
        """Test case for get_public_previews

        Get previews for a public webpage
        """
        pass

    def test_get_public_webpage(self) -> None:
        """Test case for get_public_webpage

        Get a public webpage by slug
        """
        pass

    def test_get_public_webpage_by_uuid(self) -> None:
        """Test case for get_public_webpage_by_uuid

        Get a public webpage by UUID
        """
        pass

    def test_get_public_webpage_protection(self) -> None:
        """Test case for get_public_webpage_protection

        Get webpage protection metadata
        """
        pass

    def test_get_template_webpage(self) -> None:
        """Test case for get_template_webpage

        Get template webpage
        """
        pass

    def test_get_template_webpage_editing_status(self) -> None:
        """Test case for get_template_webpage_editing_status

        Check if a template webpage is being edited
        """
        pass

    def test_get_webpage(self) -> None:
        """Test case for get_webpage

        Get webpage details
        """
        pass

    def test_get_webpage_editing_status(self) -> None:
        """Test case for get_webpage_editing_status

        Check if a webpage is being edited
        """
        pass

    def test_get_webpage_picker_pages(self) -> None:
        """Test case for get_webpage_picker_pages

        List webpages for picker dropdowns
        """
        pass

    def test_list_protection_grants(self) -> None:
        """Test case for list_protection_grants

        List signed URL grants for a webpage
        """
        pass

    def test_publish_webpage(self) -> None:
        """Test case for publish_webpage

        Publish a webpage
        """
        pass

    def test_release_template_webpage_editing_session(self) -> None:
        """Test case for release_template_webpage_editing_session

        Release a template webpage editing session
        """
        pass

    def test_release_webpage_editing_session(self) -> None:
        """Test case for release_webpage_editing_session

        Release a webpage editing session
        """
        pass

    def test_revoke_protection_grant(self) -> None:
        """Test case for revoke_protection_grant

        Revoke a signed URL grant
        """
        pass

    def test_unlock_public_webpage(self) -> None:
        """Test case for unlock_public_webpage

        Unlock password-protected webpage
        """
        pass

    def test_unpublish_webpage(self) -> None:
        """Test case for unpublish_webpage

        Unpublish a webpage
        """
        pass

    def test_update_webpage(self) -> None:
        """Test case for update_webpage

        Update a webpage
        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        Upload a file for a webpage
        """
        pass

    def test_upload_file1(self) -> None:
        """Test case for upload_file1

        Upload a file
        """
        pass


if __name__ == '__main__':
    unittest.main()
