# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.webpage_map_locations_dto import WebpageMapLocationsDTO

class TestWebpageMapLocationsDTO(unittest.TestCase):
    """WebpageMapLocationsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebpageMapLocationsDTO:
        """Test WebpageMapLocationsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebpageMapLocationsDTO`
        """
        model = WebpageMapLocationsDTO()
        if include_optional:
            return WebpageMapLocationsDTO(
                map_locations = [
                    caraer_client.models.map_location_dto.MapLocationDTO(
                        latitude = 1.337, 
                        longitude = 1.337, 
                        property_uuid = '', 
                        property_name = '', 
                        object_uuid = '', 
                        object_name = '', 
                        icon = '', 
                        icon_color = '', 
                        icon_background_color = '', 
                        marker_size = 1.337, 
                        icon_size = 1.337, 
                        label = '', 
                        label_property_uuid = '', 
                        label_property_name = '', 
                        hover_preview_uuid = '', 
                        hover_preview_name = '', 
                        record_uuid = '', 
                        click_link_type = '', 
                        click_link_url = '', 
                        click_link_open_in_new_window = True, 
                        href = '', 
                        filter_properties = [
                            caraer_client.models.property_dto.PropertyDTO(
                                uuid = '0', 
                                name = '', 
                                label = '', 
                                created_at = 56, 
                                created_by = null, 
                                updated_at = 56, 
                                updated_by = null, 
                                deleted_at = 56, 
                                deleted_by = null, 
                                index = 56, 
                                description = '', 
                                type = '', 
                                options = [
                                    caraer_client.models.property_option.PropertyOption(
                                        name = '', 
                                        label = '', 
                                        icon = '', 
                                        color = '', 
                                        disabled = True, 
                                        completed = True, 
                                        used_in = caraer_client.models.used_in_result.UsedInResult(
                                            record_uuids = [
                                                ''
                                                ], 
                                            count = 56, ), )
                                    ], 
                                group = '', 
                                format = null, 
                                rules = [
                                    ''
                                    ], 
                                immutable = True, 
                                hidden = True, 
                                lifecycle_active = True, 
                                required_filter = null, 
                                non_public = True, 
                                indexed = True, 
                                editable = True, 
                                format_settings = {
                                    'key' : null
                                    }, 
                                used_in = null, 
                                icon = '', 
                                webpage_public = True, 
                                embeddable = True, 
                                sensitive = True, 
                                min_and_max_value = null, 
                                pinned = True, )
                            ], 
                        filter_values = {
                            'key' : null
                            }, )
                    ]
            )
        else:
            return WebpageMapLocationsDTO(
        )
        """

    def testWebpageMapLocationsDTO(self):
        """Test WebpageMapLocationsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
