# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.webpage_editing_status_dto import WebpageEditingStatusDTO

class TestWebpageEditingStatusDTO(unittest.TestCase):
    """WebpageEditingStatusDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebpageEditingStatusDTO:
        """Test WebpageEditingStatusDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebpageEditingStatusDTO`
        """
        model = WebpageEditingStatusDTO()
        if include_optional:
            return WebpageEditingStatusDTO(
                locked = True,
                editor = caraer_client.models.user_with_cursor_location_dto.UserWithCursorLocationDTO(
                    uuid = '', 
                    email = '', 
                    firstname = '', 
                    lastname = '', 
                    cursor_location = caraer_client.models.cursor_location.CursorLocation(
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, ), 
                    reference = '', 
                    session_id = '', ),
                message = ''
            )
        else:
            return WebpageEditingStatusDTO(
        )
        """

    def testWebpageEditingStatusDTO(self):
        """Test WebpageEditingStatusDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
