# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.flow_pagination_request import FlowPaginationRequest

class TestFlowPaginationRequest(unittest.TestCase):
    """FlowPaginationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowPaginationRequest:
        """Test FlowPaginationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowPaginationRequest`
        """
        model = FlowPaginationRequest()
        if include_optional:
            return FlowPaginationRequest(
                crud = caraer_client.models.crud.CRUD(
                    session_type = 'MAIN', 
                    http_session_id = '', 
                    turn_off_meta_relationships = True, ),
                show_items = [
                    caraer_client.models.show_item.ShowItem(
                        object = 'User', 
                        relation = 'hasProperty', 
                        relation_direction = 'outgoing', 
                        property = 'email', 
                        separator = '|', 
                        sticky = True, 
                        width = 100, 
                        calculation_function = 'max', 
                        calculation_result = 100, )
                    ],
                page = 1,
                limit = 10,
                filter = caraer_client.models.filter.Filter(
                    groups = [
                        caraer_client.models.filter_group.FilterGroup(
                            items = null, )
                        ], ),
                sort = [
                    caraer_client.models.sort_item.SortItem(
                        object = 'User', 
                        relation = 'hasProperty', 
                        relation_direction = 'outgoing', 
                        property = 'email', 
                        direction = 'ASC', )
                    ],
                show = [
                    caraer_client.models.show_item.ShowItem(
                        object = 'User', 
                        relation = 'hasProperty', 
                        relation_direction = 'outgoing', 
                        property = 'email', 
                        separator = '|', 
                        sticky = True, 
                        width = 100, 
                        calculation_function = 'max', 
                        calculation_result = 100, )
                    ],
                query = 'keyword',
                preview = 'summary preview',
                main_object = 'user',
                column = 'status',
                var_property = '123e4567-e89b-12d3-a456-426614174000'
            )
        else:
            return FlowPaginationRequest(
        )
        """

    def testFlowPaginationRequest(self):
        """Test FlowPaginationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
