# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.not_found_error_cause_stack_trace_inner import NotFoundErrorCauseStackTraceInner

class TestNotFoundErrorCauseStackTraceInner(unittest.TestCase):
    """NotFoundErrorCauseStackTraceInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotFoundErrorCauseStackTraceInner:
        """Test NotFoundErrorCauseStackTraceInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotFoundErrorCauseStackTraceInner`
        """
        model = NotFoundErrorCauseStackTraceInner()
        if include_optional:
            return NotFoundErrorCauseStackTraceInner(
                class_loader_name = '',
                module_name = '',
                module_version = '',
                method_name = '',
                file_name = '',
                line_number = 56,
                class_name = '',
                native_method = True
            )
        else:
            return NotFoundErrorCauseStackTraceInner(
        )
        """

    def testNotFoundErrorCauseStackTraceInner(self):
        """Test NotFoundErrorCauseStackTraceInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
