# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.success_response_list_file_list_item_dto import SuccessResponseListFileListItemDTO

class TestSuccessResponseListFileListItemDTO(unittest.TestCase):
    """SuccessResponseListFileListItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponseListFileListItemDTO:
        """Test SuccessResponseListFileListItemDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessResponseListFileListItemDTO`
        """
        model = SuccessResponseListFileListItemDTO()
        if include_optional:
            return SuccessResponseListFileListItemDTO(
                message = 'Success',
                data = [
                    caraer_client.models.file_list_item_dto.FileListItemDTO(
                        key = '', 
                        name = '', 
                        size = 56, 
                        last_modified = 56, 
                        content_type = '', )
                    ]
            )
        else:
            return SuccessResponseListFileListItemDTO(
        )
        """

    def testSuccessResponseListFileListItemDTO(self):
        """Test SuccessResponseListFileListItemDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
