# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.object_access_grant_request_dto import ObjectAccessGrantRequestDTO

class TestObjectAccessGrantRequestDTO(unittest.TestCase):
    """ObjectAccessGrantRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectAccessGrantRequestDTO:
        """Test ObjectAccessGrantRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectAccessGrantRequestDTO`
        """
        model = ObjectAccessGrantRequestDTO()
        if include_optional:
            return ObjectAccessGrantRequestDTO(
                users = caraer_client.models.object_access_grant_section_dto.ObjectAccessGrantSectionDTO(
                    uuids = [
                        ''
                        ], 
                    global_scopes = [
                        ''
                        ], 
                    overrides = {
                        'key' : [
                            ''
                            ]
                        }, ),
                teams = caraer_client.models.object_access_grant_section_dto.ObjectAccessGrantSectionDTO(
                    uuids = [
                        ''
                        ], 
                    global_scopes = [
                        ''
                        ], 
                    overrides = {
                        'key' : [
                            ''
                            ]
                        }, ),
                apps = caraer_client.models.object_access_grant_section_dto.ObjectAccessGrantSectionDTO(
                    uuids = [
                        ''
                        ], 
                    global_scopes = [
                        ''
                        ], 
                    overrides = {
                        'key' : [
                            ''
                            ]
                        }, )
            )
        else:
            return ObjectAccessGrantRequestDTO(
        )
        """

    def testObjectAccessGrantRequestDTO(self):
        """Test ObjectAccessGrantRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
