# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.preview_item_settings_dto import PreviewItemSettingsDTO

class TestPreviewItemSettingsDTO(unittest.TestCase):
    """PreviewItemSettingsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreviewItemSettingsDTO:
        """Test PreviewItemSettingsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreviewItemSettingsDTO`
        """
        model = PreviewItemSettingsDTO()
        if include_optional:
            return PreviewItemSettingsDTO(
                show_icon = True,
                icon_padding = 1.337,
                icon_color = '',
                icon_size = 1.337,
                default_value = '',
                editable = True,
                help_text = '',
                paragraph = '',
                show_color = True,
                show_border = True,
                button_type = '',
                show_favicon = True
            )
        else:
            return PreviewItemSettingsDTO(
        )
        """

    def testPreviewItemSettingsDTO(self):
        """Test PreviewItemSettingsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
