# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.cms_module_dto import CmsModuleDTO

class TestCmsModuleDTO(unittest.TestCase):
    """CmsModuleDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CmsModuleDTO:
        """Test CmsModuleDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CmsModuleDTO`
        """
        model = CmsModuleDTO()
        if include_optional:
            return CmsModuleDTO(
                uuid = '',
                name = '',
                label = '',
                ref = '',
                kind = '',
                description = '',
                category = '',
                icon = '',
                preview = '',
                app_uuid = '',
                app_name = '',
                app_label = '',
                package_name = '',
                version = '',
                retired = True,
                fields = [
                    caraer_client.models.app_setting_field_schema.AppSettingFieldSchema(
                        name = '', 
                        label = '', 
                        type = '', 
                        required = True, 
                        help_text = '', 
                        options = [
                            caraer_client.models.setting_option.SettingOption(
                                name = '', 
                                label = '', 
                                help_text = '', 
                                preview = '', )
                            ], 
                        options_source = caraer_client.models.app_setting_options_source.AppSettingOptionsSource(
                            type = '', 
                            serverless_function_uuid = '', 
                            serverless_function_name = '', 
                            depends_on = [
                                ''
                                ], 
                            searchable = True, 
                            min_query_length = 56, ), 
                        action_source = caraer_client.models.app_setting_action_source.AppSettingActionSource(
                            type = '', 
                            serverless_function_uuid = '', 
                            serverless_function_name = '', 
                            enqueue = True, ), 
                        default_value = null, 
                        hidden = True, 
                        advanced = True, 
                        filter_traits = [
                            ''
                            ], 
                        visible_when = [
                            caraer_client.models.app_setting_condition.AppSettingCondition(
                                field = '', 
                                operator = '', 
                                value = null, )
                            ], 
                        item_fields = [
                            caraer_client.models.app_setting_field_schema.AppSettingFieldSchema(
                                name = '', 
                                label = '', 
                                type = '', 
                                required = True, 
                                help_text = '', 
                                default_value = null, 
                                hidden = True, 
                                advanced = True, 
                                min = 56, 
                                max = 56, 
                                item_label = '', 
                                value = null, 
                                has_value = True, 
                                mapping_value = caraer_client.models.app_setting_field_mapping_structure.AppSettingFieldMappingStructure(
                                    object_name = '', 
                                    target_kind = '', 
                                    items = [
                                        caraer_client.models.app_setting_field_mapping_structure_item.AppSettingFieldMappingStructureItem(
                                            field_label = '', 
                                            field_name = '', 
                                            field_help_text = '', 
                                            is_required = True, 
                                            allowed_property_types = [
                                                ''
                                                ], 
                                            allowed_property_formats = [
                                                ''
                                                ], 
                                            property_name = '', 
                                            record_uuid = '', )
                                        ], 
                                    record_target = True, ), 
                                value_scope = '', 
                                action = True, )
                            ], 
                        min = 56, 
                        max = 56, 
                        item_label = '', 
                        value = null, 
                        has_value = True, 
                        mapping_value = caraer_client.models.app_setting_field_mapping_structure.AppSettingFieldMappingStructure(
                            object_name = '', 
                            target_kind = '', 
                            record_target = True, ), 
                        value_scope = '', 
                        action = True, )
                    ],
                frameworks = {
                    'key' : ''
                    }
            )
        else:
            return CmsModuleDTO(
        )
        """

    def testCmsModuleDTO(self):
        """Test CmsModuleDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
