# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.relation_dto import RelationDTO

class TestRelationDTO(unittest.TestCase):
    """RelationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RelationDTO:
        """Test RelationDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RelationDTO`
        """
        model = RelationDTO()
        if include_optional:
            return RelationDTO(
                uuid = '0',
                name = '',
                label = '',
                created_at = 56,
                created_by = caraer_client.models.record.Record(
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    deleted_at = 56, 
                    created_by_uuid = '', 
                    updated_by_uuid = '', 
                    deleted_by_uuid = '', 
                    index = 56, 
                    deleted = True, 
                    complete = True, 
                    uuid = '0', 
                    user = caraer_client.models.public_user_dto.PublicUserDTO(
                        uuid = '', 
                        email = '', 
                        firstname = '', 
                        lastname = '', 
                        initials = '', 
                        scopes = [
                            ''
                            ], 
                        filters = {
                            'key' : caraer_client.models.filter.Filter(
                                groups = [
                                    caraer_client.models.filter_group.FilterGroup(
                                        items = null, )
                                    ], )
                            }, 
                        role = '', 
                        record = caraer_client.models.record.Record(
                            name = '0', 
                            label = '', 
                            created_at = 56, 
                            updated_at = 56, 
                            deleted_at = 56, 
                            created_by_uuid = '', 
                            updated_by_uuid = '', 
                            deleted_by_uuid = '', 
                            index = 56, 
                            deleted = True, 
                            complete = True, 
                            uuid = '0', 
                            properties = [
                                caraer_client.models.filled_property.FilledProperty(
                                    icon = '', 
                                    name = '', 
                                    value = null, 
                                    type = '', 
                                    label = '', )
                                ], 
                            objects = {
                                'key' : null
                                }, ), ), 
                    properties = [
                        caraer_client.models.filled_property.FilledProperty(
                            icon = '', 
                            name = '', 
                            value = null, 
                            type = '', 
                            label = '', )
                        ], 
                    objects = {
                        'key' : null
                        }, ),
                updated_at = 56,
                updated_by = caraer_client.models.record.Record(
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    deleted_at = 56, 
                    created_by_uuid = '', 
                    updated_by_uuid = '', 
                    deleted_by_uuid = '', 
                    index = 56, 
                    deleted = True, 
                    complete = True, 
                    uuid = '0', 
                    user = caraer_client.models.public_user_dto.PublicUserDTO(
                        uuid = '', 
                        email = '', 
                        firstname = '', 
                        lastname = '', 
                        initials = '', 
                        scopes = [
                            ''
                            ], 
                        filters = {
                            'key' : caraer_client.models.filter.Filter(
                                groups = [
                                    caraer_client.models.filter_group.FilterGroup(
                                        items = null, )
                                    ], )
                            }, 
                        role = '', 
                        record = caraer_client.models.record.Record(
                            name = '0', 
                            label = '', 
                            created_at = 56, 
                            updated_at = 56, 
                            deleted_at = 56, 
                            created_by_uuid = '', 
                            updated_by_uuid = '', 
                            deleted_by_uuid = '', 
                            index = 56, 
                            deleted = True, 
                            complete = True, 
                            uuid = '0', 
                            properties = [
                                caraer_client.models.filled_property.FilledProperty(
                                    icon = '', 
                                    name = '', 
                                    value = null, 
                                    type = '', 
                                    label = '', )
                                ], 
                            objects = {
                                'key' : null
                                }, ), ), 
                    properties = [
                        caraer_client.models.filled_property.FilledProperty(
                            icon = '', 
                            name = '', 
                            value = null, 
                            type = '', 
                            label = '', )
                        ], 
                    objects = {
                        'key' : null
                        }, ),
                deleted_at = 56,
                deleted_by = caraer_client.models.record.Record(
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    deleted_at = 56, 
                    created_by_uuid = '', 
                    updated_by_uuid = '', 
                    deleted_by_uuid = '', 
                    index = 56, 
                    deleted = True, 
                    complete = True, 
                    uuid = '0', 
                    user = caraer_client.models.public_user_dto.PublicUserDTO(
                        uuid = '', 
                        email = '', 
                        firstname = '', 
                        lastname = '', 
                        initials = '', 
                        scopes = [
                            ''
                            ], 
                        filters = {
                            'key' : caraer_client.models.filter.Filter(
                                groups = [
                                    caraer_client.models.filter_group.FilterGroup(
                                        items = null, )
                                    ], )
                            }, 
                        role = '', 
                        record = caraer_client.models.record.Record(
                            name = '0', 
                            label = '', 
                            created_at = 56, 
                            updated_at = 56, 
                            deleted_at = 56, 
                            created_by_uuid = '', 
                            updated_by_uuid = '', 
                            deleted_by_uuid = '', 
                            index = 56, 
                            deleted = True, 
                            complete = True, 
                            uuid = '0', 
                            properties = [
                                caraer_client.models.filled_property.FilledProperty(
                                    icon = '', 
                                    name = '', 
                                    value = null, 
                                    type = '', 
                                    label = '', )
                                ], 
                            objects = {
                                'key' : null
                                }, ), ), 
                    properties = [
                        caraer_client.models.filled_property.FilledProperty(
                            icon = '', 
                            name = '', 
                            value = null, 
                            type = '', 
                            label = '', )
                        ], 
                    objects = {
                        'key' : null
                        }, ),
                index = 56,
                description = '',
                objects = [
                    caraer_client.models.caraer_object_dto.CaraerObjectDTO(
                        uuid = '0', 
                        name = '', 
                        label = '', 
                        created_at = 56, 
                        created_by = null, 
                        updated_at = 56, 
                        updated_by = null, 
                        deleted_at = 56, 
                        deleted_by = null, 
                        index = 56, 
                        plural = '', 
                        description = '', 
                        groups = [
                            ''
                            ], 
                        icon = '', 
                        show_in_menu = True, 
                        default_trait = '', 
                        traits = [
                            ''
                            ], 
                        views = [
                            caraer_client.models.view_dto.ViewDTO(
                                uuid = '0', 
                                name = '', 
                                label = '', 
                                created_at = 56, 
                                created_by = null, 
                                updated_at = 56, 
                                updated_by = null, 
                                deleted_at = 56, 
                                deleted_by = null, 
                                index = 56, 
                                favorite = True, 
                                team = True, 
                                shared = True, 
                                personal = True, 
                                trait = '', 
                                filters = caraer_client.models.filter.Filter(), 
                                shows = [
                                    caraer_client.models.show_item.ShowItem(
                                        object = 'User', 
                                        relation = 'hasProperty', 
                                        relation_direction = 'outgoing', 
                                        property = 'email', 
                                        separator = '|', 
                                        sticky = True, 
                                        width = 100, 
                                        calculation_function = 'max', 
                                        calculation_result = 100, )
                                    ], 
                                sorts = [
                                    caraer_client.models.sort_item.SortItem(
                                        object = 'User', 
                                        relation = 'hasProperty', 
                                        relation_direction = 'outgoing', 
                                        property = 'email', 
                                        direction = 'ASC', )
                                    ], 
                                limit = 56, 
                                show_icons = True, 
                                row_height = '', 
                                query = '', 
                                icon = '', 
                                flow_property = '', 
                                flow_preview = '', 
                                task_progress_property = '', 
                                task_group_property = '', 
                                task_expand_subtasks = True, 
                                task_collapsed_group_keys = [
                                    ''
                                    ], 
                                task_expanded_task_uuids = [
                                    ''
                                    ], 
                                default_view = True, 
                                is_internally_public = True, 
                                analytics = caraer_client.models.analytics_dashboard_config.AnalyticsDashboardConfig(
                                    version = 56, 
                                    columns = 56, 
                                    widgets = [
                                        caraer_client.models.analytics_widget_config.AnalyticsWidgetConfig(
                                            id = '', 
                                            title = '', 
                                            chart_type = '', 
                                            main_object = '', 
                                            x = 56, 
                                            y = 56, 
                                            w = 56, 
                                            h = 56, 
                                            filter = caraer_client.models.filter.Filter(), 
                                            x_axis = caraer_client.models.analytics_axis_config.AnalyticsAxisConfig(
                                                property = caraer_client.models.analytics_property_ref.AnalyticsPropertyRef(
                                                    object = '', 
                                                    relation = '', 
                                                    property_name = '', ), 
                                                time_bucket = '', 
                                                time_zone = '', 
                                                window_days = 56, 
                                                bin_count = 56, 
                                                metric = '', 
                                                label = '', ), 
                                            y_axis = caraer_client.models.analytics_axis_config.AnalyticsAxisConfig(
                                                time_bucket = '', 
                                                time_zone = '', 
                                                window_days = 56, 
                                                bin_count = 56, 
                                                metric = '', 
                                                label = '', ), 
                                            series = caraer_client.models.analytics_series_config.AnalyticsSeriesConfig(
                                                group_by = caraer_client.models.analytics_property_ref.AnalyticsPropertyRef(
                                                    object = '', 
                                                    relation = '', 
                                                    property_name = '', ), ), 
                                            comparison_metrics = [
                                                caraer_client.models.analytics_comparison_metric.AnalyticsComparisonMetric(
                                                    key = '', 
                                                    label = '', 
                                                    main_object = '', )
                                                ], 
                                            trend = caraer_client.models.analytics_trend_config.AnalyticsTrendConfig(
                                                window_days = 56, ), 
                                            limit = 56, 
                                            sort = '', 
                                            exclude_empty_values = True, 
                                            style = caraer_client.models.analytics_widget_style.AnalyticsWidgetStyle(
                                                show_legend = True, 
                                                show_grid = True, 
                                                show_value_labels = True, 
                                                bar_orientation = '', 
                                                bar_grouping = '', 
                                                colors = {
                                                    'key' : ''
                                                    }, 
                                                reference_lines = [
                                                    caraer_client.models.analytics_reference_line.AnalyticsReferenceLine(
                                                        value = 1.337, 
                                                        label = '', 
                                                        color = '', )
                                                    ], ), )
                                        ], ), )
                            ], 
                        properties = [
                            caraer_client.models.property_dto.PropertyDTO(
                                uuid = '0', 
                                name = '', 
                                label = '', 
                                created_at = 56, 
                                created_by = null, 
                                updated_at = 56, 
                                updated_by = null, 
                                deleted_at = 56, 
                                deleted_by = null, 
                                index = 56, 
                                description = '', 
                                type = '', 
                                options = [
                                    caraer_client.models.property_option.PropertyOption(
                                        name = '', 
                                        label = '', 
                                        icon = '', 
                                        color = '', 
                                        disabled = True, 
                                        completed = True, 
                                        used_in = caraer_client.models.used_in_result.UsedInResult(
                                            record_uuids = [
                                                ''
                                                ], 
                                            count = 56, ), )
                                    ], 
                                group = '', 
                                format = null, 
                                rules = [
                                    ''
                                    ], 
                                immutable = True, 
                                hidden = True, 
                                lifecycle_active = True, 
                                required_filter = null, 
                                non_public = True, 
                                indexed = True, 
                                editable = True, 
                                format_settings = {
                                    'key' : null
                                    }, 
                                used_in = null, 
                                icon = '', 
                                webpage_public = True, 
                                embeddable = True, 
                                sensitive = True, 
                                min_and_max_value = null, 
                                pinned = True, )
                            ], 
                        relations = [
                            caraer_client.models.relation_dto.RelationDTO(
                                uuid = '0', 
                                name = '', 
                                label = '', 
                                created_at = 56, 
                                created_by = null, 
                                updated_at = 56, 
                                updated_by = null, 
                                deleted_at = 56, 
                                deleted_by = null, 
                                index = 56, 
                                description = '', 
                                immutable = True, 
                                editable = True, )
                            ], 
                        suites = [
                            ''
                            ], 
                        extends_to = [
                            caraer_client.models.caraer_object_dto.CaraerObjectDTO(
                                uuid = '0', 
                                name = '', 
                                label = '', 
                                created_at = 56, 
                                created_by = null, 
                                updated_at = 56, 
                                updated_by = null, 
                                deleted_at = 56, 
                                deleted_by = null, 
                                index = 56, 
                                plural = '', 
                                description = '', 
                                icon = '', 
                                show_in_menu = True, 
                                default_trait = '', 
                                editable = True, )
                            ], 
                        editable = True, )
                    ],
                immutable = True,
                editable = True
            )
        else:
            return RelationDTO(
                uuid = '0',
        )
        """

    def testRelationDTO(self):
        """Test RelationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
