# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_dismiss_notification(self) -> None:
        """Test case for dismiss_notification

        Dismiss a notification
        """
        pass

    def test_firebase_token(self) -> None:
        """Test case for firebase_token

        Mint a Firebase custom token so the app can listen to its inbox
        """
        pass

    def test_list_notifications(self) -> None:
        """Test case for list_notifications

        List in-app notifications for the logged-in user
        """
        pass

    def test_mark_all_as_read(self) -> None:
        """Test case for mark_all_as_read

        Mark all notifications as read for the current company
        """
        pass

    def test_mark_as_read(self) -> None:
        """Test case for mark_as_read

        Mark a notification as read
        """
        pass

    def test_send_notification(self) -> None:
        """Test case for send_notification

        Send a notification (app token)
        """
        pass


if __name__ == '__main__':
    unittest.main()
