# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.api.module_api import ModuleApi


class TestModuleApi(unittest.TestCase):
    """ModuleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModuleApi()

    def tearDown(self) -> None:
        pass

    def test_create_module(self) -> None:
        """Test case for create_module

        Create a new module
        """
        pass

    def test_create_personal_module(self) -> None:
        """Test case for create_personal_module

        Create a personal module
        """
        pass

    def test_delete_module(self) -> None:
        """Test case for delete_module

        Delete a module
        """
        pass

    def test_delete_personal_module(self) -> None:
        """Test case for delete_personal_module

        Delete a personal module
        """
        pass

    def test_get_module(self) -> None:
        """Test case for get_module

        Fetch a specific module
        """
        pass

    def test_get_modules(self) -> None:
        """Test case for get_modules

        Fetch paginated modules
        """
        pass

    def test_get_personal_module(self) -> None:
        """Test case for get_personal_module

        Fetch a personal module
        """
        pass

    def test_get_personal_modules(self) -> None:
        """Test case for get_personal_modules

        Fetch paginated personal modules
        """
        pass

    def test_update_module(self) -> None:
        """Test case for update_module

        Update an existing module
        """
        pass

    def test_update_personal_module(self) -> None:
        """Test case for update_personal_module

        Update a personal module
        """
        pass


if __name__ == '__main__':
    unittest.main()
