# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.bulk_edit_record_item import BulkEditRecordItem

class TestBulkEditRecordItem(unittest.TestCase):
    """BulkEditRecordItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkEditRecordItem:
        """Test BulkEditRecordItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkEditRecordItem`
        """
        model = BulkEditRecordItem()
        if include_optional:
            return BulkEditRecordItem(
                uuid = '',
                client_ref = '',
                properties = {email=a@b.com},
                relations = [
                    caraer_client.models.record_relation_request_dto.RecordRelationRequestDTO(
                        relation_name = 'works_at', 
                        uuid = '', 
                        properties = {
                            'key' : null
                            }, 
                        edge_properties = {partstat=ACCEPTED}, 
                        record = null, 
                        object_name = '', 
                        primary = False, 
                        merge = True, )
                    ]
            )
        else:
            return BulkEditRecordItem(
        )
        """

    def testBulkEditRecordItem(self):
        """Test BulkEditRecordItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
