# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.crud import CRUD

class TestCRUD(unittest.TestCase):
    """CRUD unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CRUD:
        """Test CRUD
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CRUD`
        """
        model = CRUD()
        if include_optional:
            return CRUD(
                session_type = 'MAIN',
                http_session_id = '',
                turn_off_meta_relationships = True
            )
        else:
            return CRUD(
        )
        """

    def testCRUD(self):
        """Test CRUD"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
