# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.app_dto import AppDTO

class TestAppDTO(unittest.TestCase):
    """AppDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppDTO:
        """Test AppDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppDTO`
        """
        model = AppDTO()
        if include_optional:
            return AppDTO(
                uuid = '0',
                name = '0',
                label = '',
                created_at = 56,
                created_by = caraer_client.models.record.Record(
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    deleted_at = 56, 
                    created_by_uuid = '', 
                    updated_by_uuid = '', 
                    deleted_by_uuid = '', 
                    index = 56, 
                    deleted = True, 
                    complete = True, 
                    uuid = '0', 
                    properties = [
                        caraer_client.models.filled_property.FilledProperty(
                            name = '', 
                            value = null, 
                            type = '', 
                            icon = '', 
                            label = '', )
                        ], 
                    objects = {
                        'key' : null
                        }, 
                    user = caraer_client.models.public_user_dto.PublicUserDTO(
                        uuid = '', 
                        email = '', 
                        firstname = '', 
                        lastname = '', 
                        initials = '', 
                        scopes = [
                            ''
                            ], 
                        filters = {
                            'key' : caraer_client.models.filter.Filter(
                                groups = [
                                    caraer_client.models.filter_group.FilterGroup(
                                        items = null, )
                                    ], )
                            }, 
                        role = '', 
                        record = caraer_client.models.record.Record(
                            name = '0', 
                            label = '', 
                            created_at = 56, 
                            updated_at = 56, 
                            deleted_at = 56, 
                            created_by_uuid = '', 
                            updated_by_uuid = '', 
                            deleted_by_uuid = '', 
                            index = 56, 
                            deleted = True, 
                            complete = True, 
                            uuid = '0', ), ), ),
                updated_at = 56,
                updated_by = caraer_client.models.record.Record(
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    deleted_at = 56, 
                    created_by_uuid = '', 
                    updated_by_uuid = '', 
                    deleted_by_uuid = '', 
                    index = 56, 
                    deleted = True, 
                    complete = True, 
                    uuid = '0', 
                    properties = [
                        caraer_client.models.filled_property.FilledProperty(
                            name = '', 
                            value = null, 
                            type = '', 
                            icon = '', 
                            label = '', )
                        ], 
                    objects = {
                        'key' : null
                        }, 
                    user = caraer_client.models.public_user_dto.PublicUserDTO(
                        uuid = '', 
                        email = '', 
                        firstname = '', 
                        lastname = '', 
                        initials = '', 
                        scopes = [
                            ''
                            ], 
                        filters = {
                            'key' : caraer_client.models.filter.Filter(
                                groups = [
                                    caraer_client.models.filter_group.FilterGroup(
                                        items = null, )
                                    ], )
                            }, 
                        role = '', 
                        record = caraer_client.models.record.Record(
                            name = '0', 
                            label = '', 
                            created_at = 56, 
                            updated_at = 56, 
                            deleted_at = 56, 
                            created_by_uuid = '', 
                            updated_by_uuid = '', 
                            deleted_by_uuid = '', 
                            index = 56, 
                            deleted = True, 
                            complete = True, 
                            uuid = '0', ), ), ),
                deleted_at = 56,
                deleted_by = caraer_client.models.record.Record(
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    updated_at = 56, 
                    deleted_at = 56, 
                    created_by_uuid = '', 
                    updated_by_uuid = '', 
                    deleted_by_uuid = '', 
                    index = 56, 
                    deleted = True, 
                    complete = True, 
                    uuid = '0', 
                    properties = [
                        caraer_client.models.filled_property.FilledProperty(
                            name = '', 
                            value = null, 
                            type = '', 
                            icon = '', 
                            label = '', )
                        ], 
                    objects = {
                        'key' : null
                        }, 
                    user = caraer_client.models.public_user_dto.PublicUserDTO(
                        uuid = '', 
                        email = '', 
                        firstname = '', 
                        lastname = '', 
                        initials = '', 
                        scopes = [
                            ''
                            ], 
                        filters = {
                            'key' : caraer_client.models.filter.Filter(
                                groups = [
                                    caraer_client.models.filter_group.FilterGroup(
                                        items = null, )
                                    ], )
                            }, 
                        role = '', 
                        record = caraer_client.models.record.Record(
                            name = '0', 
                            label = '', 
                            created_at = 56, 
                            updated_at = 56, 
                            deleted_at = 56, 
                            created_by_uuid = '', 
                            updated_by_uuid = '', 
                            deleted_by_uuid = '', 
                            index = 56, 
                            deleted = True, 
                            complete = True, 
                            uuid = '0', ), ), ),
                index = 56,
                private_app = True,
                hide_api_key_field = True,
                details = caraer_client.models.app_details_dto.AppDetailsDTO(
                    title = '', 
                    description = '', 
                    image = '', 
                    brand_color = '#E74363', 
                    text_color = '#FFFFFF', 
                    url = '', 
                    category = 'productivity', 
                    subcategories = [tasks, automation], 
                    privacy_policy = '', 
                    terms_and_conditions = '', 
                    processing_agreement = '', 
                    disclaimer = '', 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
                pricing_plans = [
                    caraer_client.models.app_pricing_dto.AppPricingDTO(
                        uuid = '0', 
                        name = '0', 
                        label = '', 
                        created_at = 56, 
                        created_by = null, 
                        updated_at = 56, 
                        updated_by = null, 
                        deleted_at = 56, 
                        deleted_by = null, 
                        index = 56, 
                        title = '', 
                        description = '', 
                        pricing_type = '', 
                        price_per_unit = '', 
                        unit = '', 
                        free_units = '', 
                        free_units_period = '', 
                        tiers = [
                            caraer_client.models.app_tier_dto.AppTierDTO(
                                uuid = '0', 
                                name = '0', 
                                label = '', 
                                created_at = 56, 
                                created_by = null, 
                                updated_at = 56, 
                                updated_by = null, 
                                deleted_at = 56, 
                                deleted_by = null, 
                                index = 56, 
                                start_units = '', 
                                end_units = '', 
                                price_per_month = '', 
                                price_per_year = '', 
                                price_per_extra_unit = '', )
                            ], )
                    ],
                app_bars = [
                    caraer_client.models.app_bar_dto.AppBarDTO(
                        uuid = '0', 
                        name = '0', 
                        label = '', 
                        created_at = 56, 
                        created_by = null, 
                        updated_at = 56, 
                        updated_by = null, 
                        deleted_at = 56, 
                        deleted_by = null, 
                        index = 56, 
                        location = 'RECORD_PREVIEW', 
                        iframe_url = '', 
                        icon = '', 
                        description = '', 
                        tooltip_label = '', 
                        action_label = '', 
                        settings_schema = [
                            caraer_client.models.app_setting_field_schema.AppSettingFieldSchema(
                                name = '', 
                                label = '', 
                                type = '', 
                                required = True, 
                                help_text = '', 
                                options = [
                                    caraer_client.models.setting_option.SettingOption(
                                        name = '', 
                                        label = '', 
                                        help_text = '', )
                                    ], 
                                options_source = caraer_client.models.app_setting_options_source.AppSettingOptionsSource(
                                    type = '', 
                                    serverless_function_uuid = '', 
                                    depends_on = [
                                        ''
                                        ], 
                                    searchable = True, 
                                    min_query_length = 56, ), 
                                default_value = null, 
                                hidden = True, 
                                value = null, 
                                mapping_value = caraer_client.models.app_setting_field_mapping_structure.AppSettingFieldMappingStructure(
                                    object_name = '', 
                                    items = [
                                        caraer_client.models.app_setting_field_mapping_structure_item.AppSettingFieldMappingStructureItem(
                                            field_label = '', 
                                            field_name = '', 
                                            field_help_text = '', 
                                            is_required = True, 
                                            allowed_property_types = [
                                                ''
                                                ], 
                                            allowed_property_formats = [
                                                ''
                                                ], 
                                            property_name = '', )
                                        ], ), )
                            ], 
                        webhook = null, )
                    ],
                serverless_functions = [
                    caraer_client.models.serverless_function_dto.ServerlessFunctionDTO(
                        uuid = '0', 
                        name = '0', 
                        label = '', 
                        created_at = 56, 
                        created_by = null, 
                        updated_at = 56, 
                        updated_by = null, 
                        deleted_at = 56, 
                        deleted_by = null, 
                        index = 56, 
                        runtime = '', 
                        code = '', 
                        description = '', )
                    ],
                install_webhook = caraer_client.models.subscribe_webhook_dto.SubscribeWebhookDTO(
                    url = 'https://example.com/webhook', 
                    serverless_function = null, 
                    delivery_mode = '', 
                    secret = 'abcd1234', 
                    topic = 'user.created', 
                    description = '', 
                    webhook_format = 'LEGACY', 
                    parse_record = True, 
                    filter = null, 
                    include_relations = [candidate, vacancy], 
                    relation_filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    relation_limit = 10, 
                    retry_enabled = True, 
                    max_retries = 3, 
                    retry_backoff_ms = 1000, 
                    trigger_offset_seconds = 604800, 
                    schedule_direction = 'BEFORE', 
                    schedule_recurring = 'YEARLY', 
                    schedule_cron_expression = '0', 
                    schedule_version = 56, 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
                uninstall_webhook = caraer_client.models.subscribe_webhook_dto.SubscribeWebhookDTO(
                    url = 'https://example.com/webhook', 
                    serverless_function = null, 
                    delivery_mode = '', 
                    secret = 'abcd1234', 
                    topic = 'user.created', 
                    description = '', 
                    webhook_format = 'LEGACY', 
                    parse_record = True, 
                    filter = null, 
                    include_relations = [candidate, vacancy], 
                    relation_filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    relation_limit = 10, 
                    retry_enabled = True, 
                    max_retries = 3, 
                    retry_backoff_ms = 1000, 
                    trigger_offset_seconds = 604800, 
                    schedule_direction = 'BEFORE', 
                    schedule_recurring = 'YEARLY', 
                    schedule_cron_expression = '0', 
                    schedule_version = 56, 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
                rotate_webhook = caraer_client.models.subscribe_webhook_dto.SubscribeWebhookDTO(
                    url = 'https://example.com/webhook', 
                    serverless_function = null, 
                    delivery_mode = '', 
                    secret = 'abcd1234', 
                    topic = 'user.created', 
                    description = '', 
                    webhook_format = 'LEGACY', 
                    parse_record = True, 
                    filter = null, 
                    include_relations = [candidate, vacancy], 
                    relation_filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    relation_limit = 10, 
                    retry_enabled = True, 
                    max_retries = 3, 
                    retry_backoff_ms = 1000, 
                    trigger_offset_seconds = 604800, 
                    schedule_direction = 'BEFORE', 
                    schedule_recurring = 'YEARLY', 
                    schedule_cron_expression = '0', 
                    schedule_version = 56, 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
                update_webhook = caraer_client.models.subscribe_webhook_dto.SubscribeWebhookDTO(
                    url = 'https://example.com/webhook', 
                    serverless_function = null, 
                    delivery_mode = '', 
                    secret = 'abcd1234', 
                    topic = 'user.created', 
                    description = '', 
                    webhook_format = 'LEGACY', 
                    parse_record = True, 
                    filter = null, 
                    include_relations = [candidate, vacancy], 
                    relation_filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    relation_limit = 10, 
                    retry_enabled = True, 
                    max_retries = 3, 
                    retry_backoff_ms = 1000, 
                    trigger_offset_seconds = 604800, 
                    schedule_direction = 'BEFORE', 
                    schedule_recurring = 'YEARLY', 
                    schedule_cron_expression = '0', 
                    schedule_version = 56, 
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, ),
                settings_schema = [
                    caraer_client.models.app_setting_field_schema.AppSettingFieldSchema(
                        name = '', 
                        label = '', 
                        type = '', 
                        required = True, 
                        help_text = '', 
                        options = [
                            caraer_client.models.setting_option.SettingOption(
                                name = '', 
                                label = '', 
                                help_text = '', )
                            ], 
                        options_source = caraer_client.models.app_setting_options_source.AppSettingOptionsSource(
                            type = '', 
                            serverless_function_uuid = '', 
                            depends_on = [
                                ''
                                ], 
                            searchable = True, 
                            min_query_length = 56, ), 
                        default_value = null, 
                        hidden = True, 
                        value = null, 
                        mapping_value = caraer_client.models.app_setting_field_mapping_structure.AppSettingFieldMappingStructure(
                            object_name = '', 
                            items = [
                                caraer_client.models.app_setting_field_mapping_structure_item.AppSettingFieldMappingStructureItem(
                                    field_label = '', 
                                    field_name = '', 
                                    field_help_text = '', 
                                    is_required = True, 
                                    allowed_property_types = [
                                        ''
                                        ], 
                                    allowed_property_formats = [
                                        ''
                                        ], 
                                    property_name = '', )
                                ], ), )
                    ],
                webhook_rate_limit_per_minute = 56,
                bill_failed_webhook_requests = True,
                app_publish = caraer_client.models.app_publish_dto.AppPublishDTO(
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    publish_state = '', 
                    submitted_at = 56, 
                    reviewed_at = 56, 
                    published_at = 56, 
                    feedback = '', 
                    reviewer_notes = '', ),
                has_app = caraer_client.models.has_app_dto.HasAppDTO(
                    uuid = '', 
                    token = '', 
                    scopes = [
                        ''
                        ], 
                    settings_values = '', 
                    filters = {
                        'key' : caraer_client.models.filter.Filter(
                            groups = [
                                caraer_client.models.filter_group.FilterGroup(
                                    items = null, )
                                ], )
                        }, 
                    app_bar_visibility = {
                        'key' : caraer_client.models.app_bar_visibility_entry.AppBarVisibilityEntry(
                            objects = [
                                ''
                                ], 
                            suites = [
                                ''
                                ], )
                        }, 
                    oauth_connected = True, 
                    oauth_access_token_expires_at = 56, 
                    selected_pricing_plan_uuid = '', ),
                image = '',
                url = '',
                category = '',
                installed = True,
                required_scopes = [
                    ''
                    ],
                resolved_required_scopes = [
                    ''
                    ],
                auth_method = 'API_KEY',
                oauth_client_id = '',
                oauth_client_secret = '',
                oauth_client_secret_configured = True,
                oauth_redirect_uris = [
                    ''
                    ],
                oauth_authorize_url = '',
                oauth_token_url = '',
                install_url = '',
                brandmark = '',
                description = ''
            )
        else:
            return AppDTO(
                uuid = '0',
                name = '0',
        )
        """

    def testAppDTO(self):
        """Test AppDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
