# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.api.calendars_api import CalendarsApi


class TestCalendarsApi(unittest.TestCase):
    """CalendarsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarsApi()

    def tearDown(self) -> None:
        pass

    def test_bootstrap(self) -> None:
        """Test case for bootstrap

        Ensure calendar schema, default calendar, and event backfill
        """
        pass

    def test_create3(self) -> None:
        """Test case for create3

        Create a calendar owned by the current user
        """
        pass

    def test_list1(self) -> None:
        """Test case for list1

        List calendars visible to the current company
        """
        pass

    def test_list_teams(self) -> None:
        """Test case for list_teams

        List teams that can be linked to a calendar
        """
        pass


if __name__ == '__main__':
    unittest.main()
