# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.record_pagination_request import RecordPaginationRequest

class TestRecordPaginationRequest(unittest.TestCase):
    """RecordPaginationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordPaginationRequest:
        """Test RecordPaginationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordPaginationRequest`
        """
        model = RecordPaginationRequest()
        if include_optional:
            return RecordPaginationRequest(
                page = 1,
                limit = 10,
                filter = None,
                sort = [
                    None
                    ],
                show = [
                    None
                    ],
                query = 'keyword',
                preview = '',
                main_object = 'user',
                column = ''
            )
        else:
            return RecordPaginationRequest(
        )
        """

    def testRecordPaginationRequest(self):
        """Test RecordPaginationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
