# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.existing_widget_summary import ExistingWidgetSummary

class TestExistingWidgetSummary(unittest.TestCase):
    """ExistingWidgetSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExistingWidgetSummary:
        """Test ExistingWidgetSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExistingWidgetSummary`
        """
        model = ExistingWidgetSummary()
        if include_optional:
            return ExistingWidgetSummary(
                yproperty = '',
                ymetric = '',
                xproperty = '',
                title = '',
                chart_type = '',
                x_property = '',
                y_metric = '',
                y_property = ''
            )
        else:
            return ExistingWidgetSummary(
        )
        """

    def testExistingWidgetSummary(self):
        """Test ExistingWidgetSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
