# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from caraer_client.models.create_response_app_inbound_route_dto import CreateResponseAppInboundRouteDTO

class TestCreateResponseAppInboundRouteDTO(unittest.TestCase):
    """CreateResponseAppInboundRouteDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateResponseAppInboundRouteDTO:
        """Test CreateResponseAppInboundRouteDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateResponseAppInboundRouteDTO`
        """
        model = CreateResponseAppInboundRouteDTO()
        if include_optional:
            return CreateResponseAppInboundRouteDTO(
                message = 'Success',
                data = caraer_client.models.app_inbound_route_dto.AppInboundRouteDTO(
                    uuid = '0', 
                    name = '0', 
                    label = '', 
                    created_at = 56, 
                    created_by = null, 
                    updated_at = 56, 
                    updated_by = null, 
                    deleted_at = 56, 
                    deleted_by = null, 
                    index = 56, 
                    auth_mode = '', 
                    enqueue = True, 
                    has_shared_secret = True, 
                    shared_secret = '', 
                    serverless_function = caraer_client.models.serverless_function_ref_dto.ServerlessFunctionRefDTO(
                        uuid = '', 
                        name = '', 
                        label = '', ), )
            )
        else:
            return CreateResponseAppInboundRouteDTO(
        )
        """

    def testCreateResponseAppInboundRouteDTO(self):
        """Test CreateResponseAppInboundRouteDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
