# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AppMeterEventRequest(BaseModel):
    """
    Manual meter event for a billable line item
    """ # noqa: E501
    line_item_name: StrictStr = Field(alias="lineItemName")
    quantity: Optional[StrictInt] = Field(default=None, description="Positive unit count; defaults to 1")
    idempotency_key: Optional[StrictStr] = Field(default=None, alias="idempotencyKey")
    occurred_at: Optional[StrictStr] = Field(default=None, description="ISO-8601 timestamp; defaults to now", alias="occurredAt")
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["lineItemName", "quantity", "idempotencyKey", "occurredAt", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppMeterEventRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppMeterEventRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lineItemName": obj.get("lineItemName"),
            "quantity": obj.get("quantity"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "occurredAt": obj.get("occurredAt"),
            "metadata": obj.get("metadata")
        })
        return _obj


