# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from caraer_client.models.property_dto import PropertyDTO
from caraer_client.models.record import Record
from caraer_client.models.view_dto import ViewDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CaraerObjectDTO(BaseModel):
    """
    Data transfer object representing a Caraer object with its configuration, properties, relations, and views
    """ # noqa: E501
    uuid: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Unique identifier for the entity")
    name: Optional[StrictStr] = Field(default=None, description="Unique identifier name for the object")
    label: Optional[StrictStr] = Field(default=None, description="Display label for the object")
    created_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was created", alias="createdAt")
    created_by: Optional[Record] = Field(default=None, description="Identifier of the user who created the entity", alias="createdBy")
    updated_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was last updated", alias="updatedAt")
    updated_by: Optional[Record] = Field(default=None, description="Identifier of the user who last updated the entity", alias="updatedBy")
    deleted_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was deleted (null if not deleted)", alias="deletedAt")
    deleted_by: Optional[Record] = Field(default=None, description="Identifier of the user who deleted the entity", alias="deletedBy")
    index: Optional[StrictInt] = Field(default=None, description="Index number for ordering objects")
    plural: Optional[StrictStr] = Field(default=None, description="Plural form of the object's name, used for display purposes")
    description: Optional[StrictStr] = Field(default=None, description="Detailed description of the object's purpose and usage")
    groups: Optional[List[StrictStr]] = Field(default=None, description="Collection of group names this object belongs to")
    icon: Optional[StrictStr] = Field(default=None, description="Icon identifier for visual representation of the object")
    show_in_menu: Optional[StrictBool] = Field(default=None, description="Indicates if this object should be displayed in navigation menus", alias="showInMenu")
    default_trait: Optional[StrictStr] = Field(default=None, description="Name of the default trait applied to this object", alias="defaultTrait")
    traits: Optional[List[StrictStr]] = Field(default=None, description="List of trait names associated with this object")
    views: Optional[List[ViewDTO]] = Field(default=None, description="List of view configurations for displaying this object")
    properties: Optional[List[PropertyDTO]] = Field(default=None, description="List of properties defined for this object")
    relations: Optional[List[RelationDTO]] = Field(default=None, description="List of relations this object has with other objects")
    suites: Optional[List[StrictStr]] = Field(default=None, description="List of suite names this object belongs to")
    extends_to: Optional[List[CaraerObjectDTO]] = Field(default=None, description="List of objects this object extends to", alias="extendsTo")
    editable: Optional[StrictBool] = Field(default=None, description="When false, the object schema cannot be updated or deleted via the API")
    __properties: ClassVar[List[str]] = ["uuid", "name", "label", "createdAt", "createdBy", "updatedAt", "updatedBy", "deletedAt", "deletedBy", "index", "plural", "description", "groups", "icon", "showInMenu", "defaultTrait", "traits", "views", "properties", "relations", "suites", "extendsTo", "editable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CaraerObjectDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_by
        if self.deleted_by:
            _dict['deletedBy'] = self.deleted_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in views (list)
        _items = []
        if self.views:
            for _item_views in self.views:
                _items.append(_item_views.to_dict() if _item_views is not None else None)
            _dict['views'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in properties (list)
        _items = []
        if self.properties:
            for _item_properties in self.properties:
                _items.append(_item_properties.to_dict() if _item_properties is not None else None)
            _dict['properties'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in relations (list)
        _items = []
        if self.relations:
            for _item_relations in self.relations:
                _items.append(_item_relations.to_dict() if _item_relations is not None else None)
            _dict['relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in extends_to (list)
        _items = []
        if self.extends_to:
            for _item_extends_to in self.extends_to:
                _items.append(_item_extends_to.to_dict() if _item_extends_to is not None else None)
            _dict['extendsTo'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CaraerObjectDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "createdAt": obj.get("createdAt"),
            "createdBy": Record.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": Record.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None,
            "deletedAt": obj.get("deletedAt"),
            "deletedBy": Record.from_dict(obj["deletedBy"]) if obj.get("deletedBy") is not None else None,
            "index": obj.get("index"),
            "plural": obj.get("plural"),
            "description": obj.get("description"),
            "groups": obj.get("groups"),
            "icon": obj.get("icon"),
            "showInMenu": obj.get("showInMenu"),
            "defaultTrait": obj.get("defaultTrait"),
            "traits": obj.get("traits"),
            "views": [ViewDTO.from_dict(_item) for _item in obj["views"]] if obj.get("views") is not None else None,
            "properties": [PropertyDTO.from_dict(_item) for _item in obj["properties"]] if obj.get("properties") is not None else None,
            "relations": [RelationDTO.from_dict(_item) for _item in obj["relations"]] if obj.get("relations") is not None else None,
            "suites": obj.get("suites"),
            "extendsTo": [CaraerObjectDTO.from_dict(_item) for _item in obj["extendsTo"]] if obj.get("extendsTo") is not None else None,
            "editable": obj.get("editable")
        })
        return _obj

from caraer_client.models.relation_dto import RelationDTO
# TODO: Rewrite to not use raise_errors
CaraerObjectDTO.model_rebuild(raise_errors=False)

