# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from caraer_client.models.record import Record
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FeedDTO(BaseModel):
    """
    FeedDTO
    """ # noqa: E501
    uuid: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Unique identifier for the entity")
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The name of the entity")
    label: Optional[StrictStr] = Field(default=None, description="Display label for the entity, can be different from name")
    created_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was created", alias="createdAt")
    created_by: Optional[Record] = Field(default=None, description="Identifier of the user who created the entity", alias="createdBy")
    updated_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was last updated", alias="updatedAt")
    updated_by: Optional[Record] = Field(default=None, description="Identifier of the user who last updated the entity", alias="updatedBy")
    deleted_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was deleted (null if not deleted)", alias="deletedAt")
    deleted_by: Optional[Record] = Field(default=None, description="Identifier of the user who deleted the entity", alias="deletedBy")
    index: Optional[StrictInt] = Field(default=None, description="Index number for ordering entities")
    slug: Optional[StrictStr] = None
    format: Optional[StrictStr] = None
    main_object: Optional[StrictStr] = Field(default=None, alias="mainObject")
    is_public: Optional[StrictBool] = Field(default=None, alias="isPublic")
    public_token: Optional[StrictStr] = Field(default=None, alias="publicToken")
    filter: Optional[Any] = None
    filter_json: Optional[StrictStr] = Field(default=None, alias="filterJson")
    mapping: Optional[Any] = None
    mapping_json: Optional[StrictStr] = Field(default=None, alias="mappingJson")
    parse_record: Optional[StrictBool] = Field(default=None, alias="parseRecord")
    root_element: Optional[StrictStr] = Field(default=None, alias="rootElement")
    item_element: Optional[StrictStr] = Field(default=None, alias="itemElement")
    item_path: Optional[StrictStr] = Field(default=None, alias="itemPath")
    cache_ttl_seconds: Optional[StrictInt] = Field(default=None, alias="cacheTtlSeconds")
    active: Optional[StrictBool] = None
    direction: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = Field(default=None, alias="sourceUrl")
    source_auth_type: Optional[StrictStr] = Field(default=None, alias="sourceAuthType")
    source_auth_key: Optional[StrictStr] = Field(default=None, alias="sourceAuthKey")
    source_auth_value: Optional[StrictStr] = Field(default=None, alias="sourceAuthValue")
    source_auth_username: Optional[StrictStr] = Field(default=None, alias="sourceAuthUsername")
    import_interval: Optional[StrictStr] = Field(default=None, alias="importInterval")
    publish_mode: Optional[StrictStr] = Field(default=None, alias="publishMode")
    publish_environment: Optional[StrictStr] = Field(default=None, alias="publishEnvironment")
    publish_filter: Optional[Any] = Field(default=None, alias="publishFilter")
    publish_filter_json: Optional[StrictStr] = Field(default=None, alias="publishFilterJson")
    unpublish_filter: Optional[Any] = Field(default=None, alias="unpublishFilter")
    unpublish_filter_json: Optional[StrictStr] = Field(default=None, alias="unpublishFilterJson")
    last_import_at: Optional[StrictInt] = Field(default=None, alias="lastImportAt")
    last_import_status: Optional[StrictStr] = Field(default=None, alias="lastImportStatus")
    last_import_message: Optional[StrictStr] = Field(default=None, alias="lastImportMessage")
    last_import_json: Optional[StrictStr] = Field(default=None, alias="lastImportJson")
    import_running_at: Optional[StrictInt] = Field(default=None, alias="importRunningAt")
    next_import_at: Optional[StrictInt] = Field(default=None, alias="nextImportAt")
    warnings: Optional[List[StrictStr]] = None
    available_environments: Optional[List[StrictStr]] = Field(default=None, alias="availableEnvironments")
    sibling_import_feeds: Optional[List[StrictStr]] = Field(default=None, alias="siblingImportFeeds")
    __properties: ClassVar[List[str]] = ["uuid", "name", "label", "createdAt", "createdBy", "updatedAt", "updatedBy", "deletedAt", "deletedBy", "index", "slug", "format", "mainObject", "isPublic", "publicToken", "filter", "filterJson", "mapping", "mappingJson", "parseRecord", "rootElement", "itemElement", "itemPath", "cacheTtlSeconds", "active", "direction", "sourceUrl", "sourceAuthType", "sourceAuthKey", "sourceAuthValue", "sourceAuthUsername", "importInterval", "publishMode", "publishEnvironment", "publishFilter", "publishFilterJson", "unpublishFilter", "unpublishFilterJson", "lastImportAt", "lastImportStatus", "lastImportMessage", "lastImportJson", "importRunningAt", "nextImportAt", "warnings", "availableEnvironments", "siblingImportFeeds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeedDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_by
        if self.deleted_by:
            _dict['deletedBy'] = self.deleted_by.to_dict()
        # set to None if filter (nullable) is None
        # and model_fields_set contains the field
        if self.filter is None and "filter" in self.model_fields_set:
            _dict['filter'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['mapping'] = None

        # set to None if publish_filter (nullable) is None
        # and model_fields_set contains the field
        if self.publish_filter is None and "publish_filter" in self.model_fields_set:
            _dict['publishFilter'] = None

        # set to None if unpublish_filter (nullable) is None
        # and model_fields_set contains the field
        if self.unpublish_filter is None and "unpublish_filter" in self.model_fields_set:
            _dict['unpublishFilter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeedDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "createdAt": obj.get("createdAt"),
            "createdBy": Record.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": Record.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None,
            "deletedAt": obj.get("deletedAt"),
            "deletedBy": Record.from_dict(obj["deletedBy"]) if obj.get("deletedBy") is not None else None,
            "index": obj.get("index"),
            "slug": obj.get("slug"),
            "format": obj.get("format"),
            "mainObject": obj.get("mainObject"),
            "isPublic": obj.get("isPublic"),
            "publicToken": obj.get("publicToken"),
            "filter": obj.get("filter"),
            "filterJson": obj.get("filterJson"),
            "mapping": obj.get("mapping"),
            "mappingJson": obj.get("mappingJson"),
            "parseRecord": obj.get("parseRecord"),
            "rootElement": obj.get("rootElement"),
            "itemElement": obj.get("itemElement"),
            "itemPath": obj.get("itemPath"),
            "cacheTtlSeconds": obj.get("cacheTtlSeconds"),
            "active": obj.get("active"),
            "direction": obj.get("direction"),
            "sourceUrl": obj.get("sourceUrl"),
            "sourceAuthType": obj.get("sourceAuthType"),
            "sourceAuthKey": obj.get("sourceAuthKey"),
            "sourceAuthValue": obj.get("sourceAuthValue"),
            "sourceAuthUsername": obj.get("sourceAuthUsername"),
            "importInterval": obj.get("importInterval"),
            "publishMode": obj.get("publishMode"),
            "publishEnvironment": obj.get("publishEnvironment"),
            "publishFilter": obj.get("publishFilter"),
            "publishFilterJson": obj.get("publishFilterJson"),
            "unpublishFilter": obj.get("unpublishFilter"),
            "unpublishFilterJson": obj.get("unpublishFilterJson"),
            "lastImportAt": obj.get("lastImportAt"),
            "lastImportStatus": obj.get("lastImportStatus"),
            "lastImportMessage": obj.get("lastImportMessage"),
            "lastImportJson": obj.get("lastImportJson"),
            "importRunningAt": obj.get("importRunningAt"),
            "nextImportAt": obj.get("nextImportAt"),
            "warnings": obj.get("warnings"),
            "availableEnvironments": obj.get("availableEnvironments"),
            "siblingImportFeeds": obj.get("siblingImportFeeds")
        })
        return _obj


