# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FormItemDTO(BaseModel):
    """
    Represents a section or group within a form, containing a grid of form elements
    """ # noqa: E501
    aiprompt: Optional[StrictStr] = None
    title: Optional[StrictStr] = Field(default=None, description="The title or heading of this form section")
    description: Optional[StrictStr] = Field(default=None, description="Additional descriptive text explaining the purpose or instructions for this section")
    type: Optional[StrictStr] = Field(default=None, description="The type of form section (e.g., 'grid', 'section', etc.)")
    ai_prompt: Optional[StrictStr] = Field(default=None, description="The AI prompt for the form section. Only applicable to steps.", alias="AIPrompt")
    grid: Optional[List[List[GridItemDTO]]] = Field(default=None, description="A two-dimensional array representing the layout of form elements. Each inner list represents a row of elements")
    __properties: ClassVar[List[str]] = ["aiprompt", "title", "description", "type", "AIPrompt", "grid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FormItemDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in grid (list of list)
        _items = []
        if self.grid:
            for _item_grid in self.grid:
                _items.append(
                     [_inner_item.to_dict() if _inner_item is not None else None for _inner_item in _item_grid] if _item_grid is not None else None
                )
            _dict['grid'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FormItemDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aiprompt": obj.get("aiprompt"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "AIPrompt": obj.get("AIPrompt"),
            "grid": [
                    [GridItemDTO.from_dict(_inner_item) for _inner_item in _item] if _item is not None else None
                    for _item in obj["grid"]
                ] if obj.get("grid") is not None else None
        })
        return _obj

from caraer_client.models.grid_item_dto import GridItemDTO
# TODO: Rewrite to not use raise_errors
FormItemDTO.model_rebuild(raise_errors=False)

