# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from caraer_client.models.grid_item_settings_dto import GridItemSettingsDTO
from caraer_client.models.property_dto import PropertyDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GridItemDTO(BaseModel):
    """
    Represents a single cell within a form grid, which can contain a property, text, nested form, or other form elements
    """ # noqa: E501
    var_property: Optional[PropertyDTO] = Field(default=None, description="The property associated with this grid item, typically representing a form field or input", alias="property")
    text: Optional[StrictStr] = Field(default=None, description="Static text content to be displayed in this grid cell")
    form: Optional[FormDTO] = Field(default=None, description="A nested form that can be embedded within this grid cell")
    submit_button: Optional[StrictStr] = Field(default=None, description="The text of the submit button for this grid item", alias="submitButton")
    settings: Optional[GridItemSettingsDTO] = Field(default=None, description="Configuration settings for this grid item, including display and validation rules")
    value: Optional[StrictStr] = Field(default=None, description="The value of this grid item, used for form submissions")
    __properties: ClassVar[List[str]] = ["property", "text", "form", "submitButton", "settings", "value"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GridItemDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_property
        if self.var_property:
            _dict['property'] = self.var_property.to_dict()
        # override the default output from pydantic by calling `to_dict()` of form
        if self.form:
            _dict['form'] = self.form.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GridItemDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "property": PropertyDTO.from_dict(obj["property"]) if obj.get("property") is not None else None,
            "text": obj.get("text"),
            "form": FormDTO.from_dict(obj["form"]) if obj.get("form") is not None else None,
            "submitButton": obj.get("submitButton"),
            "settings": GridItemSettingsDTO.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "value": obj.get("value")
        })
        return _obj

from caraer_client.models.form_dto import FormDTO
# TODO: Rewrite to not use raise_errors
GridItemDTO.model_rebuild(raise_errors=False)

