# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Leadscore(BaseModel):
    """
    DTO representing a lead score rule
    """ # noqa: E501
    object: Optional[StrictStr] = Field(default=None, description="The name of the object to which this pagination item belongs.", json_schema_extra={"examples": ["User"]})
    relation: Optional[StrictStr] = Field(default=None, description="The relationship between objects.", json_schema_extra={"examples": ["hasProperty"]})
    relation_direction: Optional[StrictStr] = Field(default=None, description="Optional relation direction: outgoing (related→main), incoming (main→related), or omit for undirected.", alias="relationDirection", json_schema_extra={"examples": ["outgoing"]})
    var_property: Optional[StrictStr] = Field(default=None, description="The name of the property within the object.", alias="property", json_schema_extra={"examples": ["email"]})
    relation_included: Optional[StrictBool] = Field(default=None, description="Specifies whether the relation is included.", alias="relationIncluded", json_schema_extra={"examples": [True]})
    operator: Optional[StrictStr] = Field(default=None, description="Defines the operator used in the filter. Available operators are defined in the API documentation.", json_schema_extra={"examples": ["EQUALS"]})
    value: Optional[Any] = None
    smart_content: Optional[StrictBool] = Field(default=None, description="When true, filter fields contain smart content placeholders resolved at runtime.", alias="smartContent", json_schema_extra={"examples": [True]})
    edge_property: Optional[StrictBool] = Field(default=None, description="When true, propertyName refers to a property stored on the relation edge itself (declared on the relation schema, e.g. partstat on attendees) instead of a property of the related record. Requires relation and propertyName.", alias="edgeProperty", json_schema_extra={"examples": [False]})
    smart_value: Optional[StrictBool] = Field(default=None, description="Whether the value is a smart value", json_schema_extra={"examples": [True]})
    score: Optional[StrictInt] = Field(default=None, description="The score to assign if the rule is met", json_schema_extra={"examples": [10]})
    __properties: ClassVar[List[str]] = ["object", "relation", "relationDirection", "property", "relationIncluded", "operator", "value", "smartContent", "edgeProperty", "smart_value", "score"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Leadscore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Leadscore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "relation": obj.get("relation"),
            "relationDirection": obj.get("relationDirection"),
            "property": obj.get("property"),
            "relationIncluded": obj.get("relationIncluded"),
            "operator": obj.get("operator"),
            "value": obj.get("value"),
            "smartContent": obj.get("smartContent"),
            "edgeProperty": obj.get("edgeProperty"),
            "smart_value": obj.get("smart_value"),
            "score": obj.get("score")
        })
        return _obj


