# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from caraer_client.models.property_dto import PropertyDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MapLocationDTO(BaseModel):
    """
    A map marker from one source: custom lat/lng, a page location property, or an object
    """ # noqa: E501
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    property_uuid: Optional[StrictStr] = Field(default=None, description="UUID of a location property", alias="propertyUuid")
    property_name: Optional[StrictStr] = Field(default=None, description="Name of a location property (fallback if uuid missing)", alias="propertyName")
    object_uuid: Optional[StrictStr] = Field(default=None, description="When set, resolve markers from published records of this object. Exclusive with propertyUuid and custom lat/lng.", alias="objectUuid")
    object_name: Optional[StrictStr] = Field(default=None, description="Object name fallback when uuid is missing", alias="objectName")
    icon: Optional[StrictStr] = Field(default=None, description="FontAwesome icon key for the marker")
    icon_color: Optional[StrictStr] = Field(default=None, description="Marker icon color (hex or rgba)", alias="iconColor")
    icon_background_color: Optional[StrictStr] = Field(default=None, description="Marker pin background fill color (hex or rgba)", alias="iconBackgroundColor")
    marker_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Marker pin size in CSS pixels", alias="markerSize")
    icon_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Marker glyph size in CSS pixels", alias="iconSize")
    label: Optional[StrictStr] = Field(default=None, description="Text shown when hovering the marker (supports smart content)")
    label_property_uuid: Optional[StrictStr] = Field(default=None, description="UUID of a property whose value is shown as hover text", alias="labelPropertyUuid")
    label_property_name: Optional[StrictStr] = Field(default=None, description="Name of a property whose value is shown as hover text", alias="labelPropertyName")
    hover_preview_uuid: Optional[StrictStr] = Field(default=None, description="UUID of the preview shown when hovering a bound marker", alias="hoverPreviewUuid")
    hover_preview_name: Optional[StrictStr] = Field(default=None, description="Name of the preview shown when hovering a bound marker", alias="hoverPreviewName")
    record_uuid: Optional[StrictStr] = Field(default=None, description="Record this concrete public marker was resolved from", alias="recordUuid")
    click_link_type: Optional[StrictStr] = Field(default=None, description="Marker click target: liveUrl, custom, or unset", alias="clickLinkType")
    click_link_url: Optional[StrictStr] = Field(default=None, description="Custom URL used when clickLinkType is custom", alias="clickLinkUrl")
    click_link_open_in_new_window: Optional[StrictBool] = Field(default=None, description="Open the marker link in a new tab", alias="clickLinkOpenInNewWindow")
    href: Optional[StrictStr] = Field(default=None, description="Resolved public URL for this concrete marker")
    filter_properties: Optional[List[PropertyDTO]] = Field(default=None, description="Properties exposed as public filters for object-bound markers", alias="filterProperties")
    filter_values: Optional[Dict[str, Any]] = Field(default=None, description="Resolved property values used to filter this concrete marker", alias="filterValues")
    __properties: ClassVar[List[str]] = ["latitude", "longitude", "propertyUuid", "propertyName", "objectUuid", "objectName", "icon", "iconColor", "iconBackgroundColor", "markerSize", "iconSize", "label", "labelPropertyUuid", "labelPropertyName", "hoverPreviewUuid", "hoverPreviewName", "recordUuid", "clickLinkType", "clickLinkUrl", "clickLinkOpenInNewWindow", "href", "filterProperties", "filterValues"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MapLocationDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filter_properties (list)
        _items = []
        if self.filter_properties:
            for _item_filter_properties in self.filter_properties:
                _items.append(_item_filter_properties.to_dict() if _item_filter_properties is not None else None)
            _dict['filterProperties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MapLocationDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "propertyUuid": obj.get("propertyUuid"),
            "propertyName": obj.get("propertyName"),
            "objectUuid": obj.get("objectUuid"),
            "objectName": obj.get("objectName"),
            "icon": obj.get("icon"),
            "iconColor": obj.get("iconColor"),
            "iconBackgroundColor": obj.get("iconBackgroundColor"),
            "markerSize": obj.get("markerSize"),
            "iconSize": obj.get("iconSize"),
            "label": obj.get("label"),
            "labelPropertyUuid": obj.get("labelPropertyUuid"),
            "labelPropertyName": obj.get("labelPropertyName"),
            "hoverPreviewUuid": obj.get("hoverPreviewUuid"),
            "hoverPreviewName": obj.get("hoverPreviewName"),
            "recordUuid": obj.get("recordUuid"),
            "clickLinkType": obj.get("clickLinkType"),
            "clickLinkUrl": obj.get("clickLinkUrl"),
            "clickLinkOpenInNewWindow": obj.get("clickLinkOpenInNewWindow"),
            "href": obj.get("href"),
            "filterProperties": [PropertyDTO.from_dict(_item) for _item in obj["filterProperties"]] if obj.get("filterProperties") is not None else None,
            "filterValues": obj.get("filterValues")
        })
        return _obj


