# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from caraer_client.models.caraer_object_dto import CaraerObjectDTO
from caraer_client.models.filter import Filter
from caraer_client.models.form_dto import FormDTO
from caraer_client.models.preview_dto import PreviewDTO
from caraer_client.models.property_dto import PropertyDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PageContentSettingsDTO(BaseModel):
    """
    Data transfer object representing the settings for a content
    """ # noqa: E501
    form: Optional[FormDTO] = Field(default=None, description="The form associated with the content")
    open_icon: Optional[StrictStr] = Field(default=None, description="The icon to display when the accordion is open", alias="openIcon")
    close_icon: Optional[StrictStr] = Field(default=None, description="The icon to display when the accordion is closed", alias="closeIcon")
    alt: Optional[StrictStr] = Field(default=None, description="The alt text of the image")
    key: Optional[StrictStr] = Field(default=None, description="The key of the image")
    play_video: Optional[StrictBool] = Field(default=None, description="Whether the video should play automatically", alias="playVideo")
    start_muted: Optional[StrictBool] = Field(default=None, description="Whether the image should start muted", alias="startMuted")
    loop_video: Optional[StrictBool] = Field(default=None, description="Whether the video should loop", alias="loopVideo")
    start_offset: Optional[StrictInt] = Field(default=None, description="The start offset of the video", alias="startOffset")
    link: Optional[StrictStr] = Field(default=None, description="The link of the button")
    style: Optional[StrictStr] = Field(default=None, description="The style of the button. Primary, secondary, tertiary or custom")
    cta_id: Optional[StrictStr] = Field(default=None, description="Optional CTA tracking identifier for CMS buttons", alias="ctaId")
    open_in_new_window: Optional[StrictBool] = Field(default=None, description="Whether the link should open in a new window", alias="openInNewWindow")
    slider_type: Optional[StrictStr] = Field(default=None, description="The slider type. Dots, arrows and swipe", alias="sliderType")
    carousel_speed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The carousel speed.", alias="carouselSpeed")
    enable_controls: Optional[StrictBool] = Field(default=None, description="Whether carousel prev/next controls are shown", alias="enableControls")
    preview_object: Optional[CaraerObjectDTO] = Field(default=None, description="The object of the previews", alias="previewObject")
    previews: Optional[Dict[str, PreviewDTO]] = Field(default=None, description="The previews associated with the layouts")
    preview_layout_order: Optional[List[StrictStr]] = Field(default=None, description="The order of preview layouts", alias="previewLayoutOrder")
    filter: Optional[Filter] = Field(default=None, description="The filter associated with the settings")
    order_by: Optional[PropertyDTO] = Field(default=None, description="The order by property associated with the settings", alias="orderBy")
    order_by_direction: Optional[StrictStr] = Field(default=None, description="The order by direction associated with the settings. ASC or DESC, default is ASC", alias="orderByDirection")
    as_webpages: Optional[StrictBool] = Field(default=None, description="Whether the previews should be shown as webpages", alias="asWebpages")
    loop: Optional[StrictBool] = Field(default=None, description="Whether the previews should loop")
    limit: Optional[StrictInt] = Field(default=None, description="The limit associated with the settings")
    group_by: Optional[PropertyDTO] = Field(default=None, description="The group by property associated with the settings", alias="groupBy")
    hide_on_no_results: Optional[StrictBool] = Field(default=None, description="Whether the previews should be hidden when there are no results", alias="hideOnNoResults")
    filter_type: Optional[StrictStr] = Field(default=None, description="The type of the filter block. left_bar or top_search", alias="filterType")
    search_result_single_string: Optional[StrictStr] = Field(default=None, description="The single result string of the filter block", alias="searchResultSingleString")
    search_result_plural_string: Optional[StrictStr] = Field(default=None, description="The Plural result string of the filter block", alias="searchResultPluralString")
    no_results_string: Optional[StrictStr] = Field(default=None, description="The no results string of the filter block", alias="noResultsString")
    search_field_enabled: Optional[StrictBool] = Field(default=None, description="Whether the search field should be enabled", alias="searchFieldEnabled")
    search_field_placeholder: Optional[StrictStr] = Field(default=None, description="The placeholder of the search field", alias="searchFieldPlaceholder")
    filter_block_enabled: Optional[StrictBool] = Field(default=None, description="Whether the filter block should be enabled", alias="filterBlockEnabled")
    filter_title: Optional[StrictStr] = Field(default=None, description="The title of the filter block", alias="filterTitle")
    filter_subtitle: Optional[StrictStr] = Field(default=None, description="The subtitle of the filter block", alias="filterSubtitle")
    filter_properties: Optional[List[PropertyDTO]] = Field(default=None, description="The properties of the filter block", alias="filterProperties")
    enable_filter_tiles: Optional[StrictBool] = Field(default=None, description="Whether the filter tiles should be enabled", alias="enableFilterTiles")
    enable_filter_query: Optional[StrictBool] = Field(default=None, description="Whether the filter query should be enabled", alias="enableFilterQuery")
    enable_remove_all_filters_button: Optional[StrictBool] = Field(default=None, description="Whether the remove all filters button should be enabled", alias="enableRemoveAllFiltersButton")
    cta_enabled: Optional[StrictBool] = Field(default=None, description="Whether the CTA should be enabled", alias="ctaEnabled")
    cta_title: Optional[StrictStr] = Field(default=None, description="The title of the CTA", alias="ctaTitle")
    cta_text: Optional[StrictStr] = Field(default=None, description="The text of the CTA", alias="ctaText")
    cta_button_text: Optional[StrictStr] = Field(default=None, description="The button text of the CTA", alias="ctaButtonText")
    cta_button_link: Optional[StrictStr] = Field(default=None, description="The button link of the CTA", alias="ctaButtonLink")
    platforms: Optional[List[StrictStr]] = Field(default=None, description="The platforms shown in the share component")
    __properties: ClassVar[List[str]] = ["form", "openIcon", "closeIcon", "alt", "key", "playVideo", "startMuted", "loopVideo", "startOffset", "link", "style", "ctaId", "openInNewWindow", "sliderType", "carouselSpeed", "enableControls", "previewObject", "previews", "previewLayoutOrder", "filter", "orderBy", "orderByDirection", "asWebpages", "loop", "limit", "groupBy", "hideOnNoResults", "filterType", "searchResultSingleString", "searchResultPluralString", "noResultsString", "searchFieldEnabled", "searchFieldPlaceholder", "filterBlockEnabled", "filterTitle", "filterSubtitle", "filterProperties", "enableFilterTiles", "enableFilterQuery", "enableRemoveAllFiltersButton", "ctaEnabled", "ctaTitle", "ctaText", "ctaButtonText", "ctaButtonLink", "platforms"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PageContentSettingsDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of form
        if self.form:
            _dict['form'] = self.form.to_dict()
        # override the default output from pydantic by calling `to_dict()` of preview_object
        if self.preview_object:
            _dict['previewObject'] = self.preview_object.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in previews (dict)
        _field_dict = {}
        if self.previews:
            for _key_previews in self.previews:
                if self.previews[_key_previews]:
                    _field_dict[_key_previews] = self.previews[_key_previews].to_dict()
            _dict['previews'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of filter
        if self.filter:
            _dict['filter'] = self.filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order_by
        if self.order_by:
            _dict['orderBy'] = self.order_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of group_by
        if self.group_by:
            _dict['groupBy'] = self.group_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in filter_properties (list)
        _items = []
        if self.filter_properties:
            for _item_filter_properties in self.filter_properties:
                if _item_filter_properties:
                    _items.append(_item_filter_properties.to_dict())
            _dict['filterProperties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PageContentSettingsDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "form": FormDTO.from_dict(obj["form"]) if obj.get("form") is not None else None,
            "openIcon": obj.get("openIcon"),
            "closeIcon": obj.get("closeIcon"),
            "alt": obj.get("alt"),
            "key": obj.get("key"),
            "playVideo": obj.get("playVideo"),
            "startMuted": obj.get("startMuted"),
            "loopVideo": obj.get("loopVideo"),
            "startOffset": obj.get("startOffset"),
            "link": obj.get("link"),
            "style": obj.get("style"),
            "ctaId": obj.get("ctaId"),
            "openInNewWindow": obj.get("openInNewWindow"),
            "sliderType": obj.get("sliderType"),
            "carouselSpeed": obj.get("carouselSpeed"),
            "enableControls": obj.get("enableControls"),
            "previewObject": CaraerObjectDTO.from_dict(obj["previewObject"]) if obj.get("previewObject") is not None else None,
            "previews": dict(
                (_k, PreviewDTO.from_dict(_v))
                for _k, _v in obj["previews"].items()
            )
            if obj.get("previews") is not None
            else None,
            "previewLayoutOrder": obj.get("previewLayoutOrder"),
            "filter": Filter.from_dict(obj["filter"]) if obj.get("filter") is not None else None,
            "orderBy": PropertyDTO.from_dict(obj["orderBy"]) if obj.get("orderBy") is not None else None,
            "orderByDirection": obj.get("orderByDirection"),
            "asWebpages": obj.get("asWebpages"),
            "loop": obj.get("loop"),
            "limit": obj.get("limit"),
            "groupBy": PropertyDTO.from_dict(obj["groupBy"]) if obj.get("groupBy") is not None else None,
            "hideOnNoResults": obj.get("hideOnNoResults"),
            "filterType": obj.get("filterType"),
            "searchResultSingleString": obj.get("searchResultSingleString"),
            "searchResultPluralString": obj.get("searchResultPluralString"),
            "noResultsString": obj.get("noResultsString"),
            "searchFieldEnabled": obj.get("searchFieldEnabled"),
            "searchFieldPlaceholder": obj.get("searchFieldPlaceholder"),
            "filterBlockEnabled": obj.get("filterBlockEnabled"),
            "filterTitle": obj.get("filterTitle"),
            "filterSubtitle": obj.get("filterSubtitle"),
            "filterProperties": [PropertyDTO.from_dict(_item) for _item in obj["filterProperties"]] if obj.get("filterProperties") is not None else None,
            "enableFilterTiles": obj.get("enableFilterTiles"),
            "enableFilterQuery": obj.get("enableFilterQuery"),
            "enableRemoveAllFiltersButton": obj.get("enableRemoveAllFiltersButton"),
            "ctaEnabled": obj.get("ctaEnabled"),
            "ctaTitle": obj.get("ctaTitle"),
            "ctaText": obj.get("ctaText"),
            "ctaButtonText": obj.get("ctaButtonText"),
            "ctaButtonLink": obj.get("ctaButtonLink"),
            "platforms": obj.get("platforms")
        })
        return _obj


