# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from caraer_client.models.page_content_settings_dto import PageContentSettingsDTO
from caraer_client.models.page_content_styling_dto import PageContentStylingDTO
from caraer_client.models.record import Record
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PageContentDTO(BaseModel):
    """
    Data transfer object representing a webpage content
    """ # noqa: E501
    uuid: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Unique identifier for the entity")
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The name of the entity")
    label: Optional[StrictStr] = Field(default=None, description="Display label for the entity, can be different from name")
    created_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was created", alias="createdAt")
    created_by: Optional[Record] = Field(default=None, description="Identifier of the user who created the entity", alias="createdBy")
    updated_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was last updated", alias="updatedAt")
    updated_by: Optional[Record] = Field(default=None, description="Identifier of the user who last updated the entity", alias="updatedBy")
    deleted_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was deleted (null if not deleted)", alias="deletedAt")
    deleted_by: Optional[Record] = Field(default=None, description="Identifier of the user who deleted the entity", alias="deletedBy")
    index: Optional[StrictInt] = Field(default=None, description="Index number for ordering entities")
    category: Optional[StrictStr] = Field(default=None, description="Category of the content")
    parent_uuid: Optional[StrictStr] = Field(default=None, description="Unique identifier for the parent content", alias="parentUuid")
    type: Optional[StrictStr] = Field(default=None, description="Type of the content ('box' or 'component')")
    display: Optional[StrictStr] = Field(default=None, description="Display of the content for box ('column', 'row' or 'wrap') and for component ()")
    text: Optional[StrictStr] = Field(default=None, description="Text content of the content")
    custom_css: Optional[StrictStr] = Field(default=None, description="Direct CSS for this content node, scoped to data-component-uuid at render time", alias="customCss")
    styling: Optional[PageContentStylingDTO] = Field(default=None, description="Styling of the content")
    settings: Optional[PageContentSettingsDTO] = Field(default=None, description="Settings for the content")
    children: Optional[List[PageContentDTO]] = Field(default=None, description="Children of the content")
    scope: Optional[StrictStr] = Field(default=None, description="Module storage scope: company or personal")
    module_kind: Optional[StrictStr] = Field(default=None, description="Module kind: content (section/component) or page (full page design)", alias="moduleKind")
    page_custom_css: Optional[StrictStr] = Field(default=None, description="Page-level custom CSS for page modules", alias="pageCustomCss")
    page_custom_js_head: Optional[StrictStr] = Field(default=None, description="Page-level custom JS for the head for page modules", alias="pageCustomJsHead")
    page_custom_js_body: Optional[StrictStr] = Field(default=None, description="Page-level custom JS for the body for page modules", alias="pageCustomJsBody")
    sidebar_uuid: Optional[StrictStr] = Field(default=None, description="Sidebar preview UUID for page modules", alias="sidebarUuid")
    sidebar_relation_uuid: Optional[StrictStr] = Field(default=None, description="Sidebar relation UUID for page modules", alias="sidebarRelationUuid")
    sidebar_object_uuid: Optional[StrictStr] = Field(default=None, description="Sidebar object UUID for page modules", alias="sidebarObjectUuid")
    __properties: ClassVar[List[str]] = ["uuid", "name", "label", "createdAt", "createdBy", "updatedAt", "updatedBy", "deletedAt", "deletedBy", "index", "category", "parentUuid", "type", "display", "text", "customCss", "styling", "settings", "children", "scope", "moduleKind", "pageCustomCss", "pageCustomJsHead", "pageCustomJsBody", "sidebarUuid", "sidebarRelationUuid", "sidebarObjectUuid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PageContentDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_by
        if self.deleted_by:
            _dict['deletedBy'] = self.deleted_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of styling
        if self.styling:
            _dict['styling'] = self.styling.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                _items.append(_item_children.to_dict() if _item_children is not None else None)
            _dict['children'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PageContentDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "createdAt": obj.get("createdAt"),
            "createdBy": Record.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": Record.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None,
            "deletedAt": obj.get("deletedAt"),
            "deletedBy": Record.from_dict(obj["deletedBy"]) if obj.get("deletedBy") is not None else None,
            "index": obj.get("index"),
            "category": obj.get("category"),
            "parentUuid": obj.get("parentUuid"),
            "type": obj.get("type"),
            "display": obj.get("display"),
            "text": obj.get("text"),
            "customCss": obj.get("customCss"),
            "styling": PageContentStylingDTO.from_dict(obj["styling"]) if obj.get("styling") is not None else None,
            "settings": PageContentSettingsDTO.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "children": [PageContentDTO.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "scope": obj.get("scope"),
            "moduleKind": obj.get("moduleKind"),
            "pageCustomCss": obj.get("pageCustomCss"),
            "pageCustomJsHead": obj.get("pageCustomJsHead"),
            "pageCustomJsBody": obj.get("pageCustomJsBody"),
            "sidebarUuid": obj.get("sidebarUuid"),
            "sidebarRelationUuid": obj.get("sidebarRelationUuid"),
            "sidebarObjectUuid": obj.get("sidebarObjectUuid")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
PageContentDTO.model_rebuild(raise_errors=False)

