# coding: utf-8

"""
    Caraer API Documentation

    This documentation provides an overview of the Caraer API, including authentication methods, endpoint details, data models, and integration guidelines for building on the Caraer platform.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from caraer_client.models.analytics_dashboard_config import AnalyticsDashboardConfig
from caraer_client.models.filter import Filter
from caraer_client.models.record import Record
from caraer_client.models.show_item import ShowItem
from caraer_client.models.sort_item import SortItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ViewDTO(BaseModel):
    """
    ViewDTO
    """ # noqa: E501
    uuid: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Unique identifier for the entity")
    name: Optional[StrictStr] = None
    label: Optional[StrictStr] = Field(default=None, description="Display label for the entity, can be different from name")
    created_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was created", alias="createdAt")
    created_by: Optional[Record] = Field(default=None, description="Identifier of the user who created the entity", alias="createdBy")
    updated_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was last updated", alias="updatedAt")
    updated_by: Optional[Record] = Field(default=None, description="Identifier of the user who last updated the entity", alias="updatedBy")
    deleted_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp when the entity was deleted (null if not deleted)", alias="deletedAt")
    deleted_by: Optional[Record] = Field(default=None, description="Identifier of the user who deleted the entity", alias="deletedBy")
    index: Optional[StrictInt] = Field(default=None, description="Index number for ordering entities")
    favorite: Optional[StrictBool] = None
    team: Optional[StrictBool] = None
    shared: Optional[StrictBool] = None
    personal: Optional[StrictBool] = None
    trait: Optional[StrictStr] = None
    filters: Optional[Filter] = None
    shows: Optional[List[ShowItem]] = None
    sorts: Optional[List[SortItem]] = None
    limit: Optional[StrictInt] = None
    show_icons: Optional[StrictBool] = Field(default=None, alias="showIcons")
    row_height: Optional[StrictStr] = Field(default=None, alias="rowHeight")
    query: Optional[StrictStr] = None
    icon: Optional[StrictStr] = None
    flow_property: Optional[StrictStr] = Field(default=None, alias="flowProperty")
    flow_preview: Optional[StrictStr] = Field(default=None, alias="flowPreview")
    task_progress_property: Optional[StrictStr] = Field(default=None, alias="taskProgressProperty")
    task_group_property: Optional[StrictStr] = Field(default=None, alias="taskGroupProperty")
    task_expand_subtasks: Optional[StrictBool] = Field(default=None, alias="taskExpandSubtasks")
    task_collapsed_group_keys: Optional[List[StrictStr]] = Field(default=None, alias="taskCollapsedGroupKeys")
    task_expanded_task_uuids: Optional[List[StrictStr]] = Field(default=None, alias="taskExpandedTaskUuids")
    default_view: Optional[StrictBool] = Field(default=None, alias="defaultView")
    is_internally_public: Optional[StrictBool] = Field(default=None, alias="isInternallyPublic")
    analytics: Optional[AnalyticsDashboardConfig] = None
    __properties: ClassVar[List[str]] = ["uuid", "name", "label", "createdAt", "createdBy", "updatedAt", "updatedBy", "deletedAt", "deletedBy", "index", "favorite", "team", "shared", "personal", "trait", "filters", "shows", "sorts", "limit", "showIcons", "rowHeight", "query", "icon", "flowProperty", "flowPreview", "taskProgressProperty", "taskGroupProperty", "taskExpandSubtasks", "taskCollapsedGroupKeys", "taskExpandedTaskUuids", "defaultView", "isInternallyPublic", "analytics"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ViewDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_by
        if self.deleted_by:
            _dict['deletedBy'] = self.deleted_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filters
        if self.filters:
            _dict['filters'] = self.filters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in shows (list)
        _items = []
        if self.shows:
            for _item_shows in self.shows:
                _items.append(_item_shows.to_dict() if _item_shows is not None else None)
            _dict['shows'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sorts (list)
        _items = []
        if self.sorts:
            for _item_sorts in self.sorts:
                _items.append(_item_sorts.to_dict() if _item_sorts is not None else None)
            _dict['sorts'] = _items
        # override the default output from pydantic by calling `to_dict()` of analytics
        if self.analytics:
            _dict['analytics'] = self.analytics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ViewDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "createdAt": obj.get("createdAt"),
            "createdBy": Record.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": Record.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None,
            "deletedAt": obj.get("deletedAt"),
            "deletedBy": Record.from_dict(obj["deletedBy"]) if obj.get("deletedBy") is not None else None,
            "index": obj.get("index"),
            "favorite": obj.get("favorite"),
            "team": obj.get("team"),
            "shared": obj.get("shared"),
            "personal": obj.get("personal"),
            "trait": obj.get("trait"),
            "filters": Filter.from_dict(obj["filters"]) if obj.get("filters") is not None else None,
            "shows": [ShowItem.from_dict(_item) for _item in obj["shows"]] if obj.get("shows") is not None else None,
            "sorts": [SortItem.from_dict(_item) for _item in obj["sorts"]] if obj.get("sorts") is not None else None,
            "limit": obj.get("limit"),
            "showIcons": obj.get("showIcons"),
            "rowHeight": obj.get("rowHeight"),
            "query": obj.get("query"),
            "icon": obj.get("icon"),
            "flowProperty": obj.get("flowProperty"),
            "flowPreview": obj.get("flowPreview"),
            "taskProgressProperty": obj.get("taskProgressProperty"),
            "taskGroupProperty": obj.get("taskGroupProperty"),
            "taskExpandSubtasks": obj.get("taskExpandSubtasks"),
            "taskCollapsedGroupKeys": obj.get("taskCollapsedGroupKeys"),
            "taskExpandedTaskUuids": obj.get("taskExpandedTaskUuids"),
            "defaultView": obj.get("defaultView"),
            "isInternallyPublic": obj.get("isInternallyPublic"),
            "analytics": AnalyticsDashboardConfig.from_dict(obj["analytics"]) if obj.get("analytics") is not None else None
        })
        return _obj


